Make zenoh router configurable using envar
osrf/rmw_zenoh pull request #119
Opened 2024-02-27 15:12 UTC by Yadunund

This PR
- Allows users to specify a custom the `router` configuration file via the `ZENOH_ROUTER_CONFIG_URI` envar.
- The envar to specify the `session` config file is now `ZENOH_SESSION_CONFIG_URI`
- The `router` executable is now `zenohd` to align with that of upstream Zenoh.
- Readme updated to inform users how to configure these files.

Addresses https://github.com/ros2/rmw_zenoh/issues/102

2024-02-27 19:52 UTC, clalancette reviewed
I didn't do a full review here, but I did want to discuss this point:

```
The router executable is now zenohd to align with that of upstream Zenoh.
```

I'm not so sure that is a great idea.  The fact is that while this is similar to the upstream `zenohd`, it is not exactly the same and doesn't support all of the same things (in particular, plugins).  So I do think we should make it clear that this is the `rmw_zenoh_cpp` version of this.  I know that `ros2 run rmw_zenoh_cpp zenohd` does that, but:

1.  You don't have to run it that way; you can also do /path/to/zenohd, and then it looks just like the upstream one.
2.  In the process listing, it will show up as `zenohd`.  Yes, the full executable path will be to an rmw_zenoh-specific path, but it is an easy detail to overlook.

My suggestion is that we do indeed rename it, but to something else.  Something like `rmw_zenohd` or something like?

2024-02-28 03:05 UTC, Yadunund commented
> I didn't do a full review here, but I did want to discuss this point:
> 
> ```
> The router executable is now zenohd to align with that of upstream Zenoh.
> ```
> 
> I'm not so sure that is a great idea. The fact is that while this is similar to the upstream `zenohd`, it is not exactly the same and doesn't support all of the same things (in particular, plugins). So I do think we should make it clear that this is the `rmw_zenoh_cpp` version of this. I know that `ros2 run rmw_zenoh_cpp zenohd` does that, but:
> 
> 1. You don't have to run it that way; you can also do /path/to/zenohd, and then it looks just like the upstream one.
> 2. In the process listing, it will show up as `zenohd`.  Yes, the full executable path will be to an rmw_zenoh-specific path, but it is an easy detail to overlook.
> 
> My suggestion is that we do indeed rename it, but to something else. Something like `rmw_zenohd` or something like?

That makes a lot of sense to me. I've renamed the executable to `rmw_zenohd` 👍🏼

2024-02-28 12:55 UTC, clalancette requested changes
I've left a few pretty minor things to change.  Otherwise, this looks good to me.

2024-02-28 12:55 UTC, clalancette commented on README.md
> +ros2 run rmw_zenoh_cpp zenohd
```suggestion
ros2 run rmw_zenoh_cpp rmw_zenohd
```

2024-02-28 12:55 UTC, clalancette commented on README.md
> +`rmw_zenoh` relies on separate configurations files to configure the Zenoh `router` and `session` respectively. For more information on the topology of Zenoh adopted in `rmw_zenoh`, please see [Desig
```suggestion
`rmw_zenoh` relies on separate configurations files to configure the Zenoh `router` and `session` respectively.
For more information on the topology of Zenoh adopted in `rmw_zenoh`, please see [Design](#design).
Default configuration files are used by `rmw_zenoh` however certain environment variables may be set to provide absolute paths to custom configuration files.
The table below summarizes the default files and the environment variables for the `router` and `session`.
For a complete list of configurable parameters, see [zenoh/DEFAULT_CONFIG.json5](https://github.com/eclipse-zenoh/zenoh/blob/main/DEFAULT_CONFIG.json5).
```

2024-02-28 12:55 UTC, clalancette commented on README.md
> +`rmw_zenoh` relies on separate configurations files to configure the Zenoh `router` and `session` respectively. For more information on the topology of Zenoh adopted in `rmw_zenoh`, please see [Desig
It might also be worthwhile to call out what a `router` and `session` are, for those who aren't familiar with the Zenoh terminology and how rmw_zenoh use them.

2024-02-28 12:55 UTC, clalancette commented on README.md
> +By default, all discovery traffic is local per host where host is the PC running a Zenoh `router`.
```suggestion
By default, all discovery traffic is local per host, where the host is the PC running a Zenoh `router`.
```

2024-02-28 12:55 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/zenoh_config.hpp
> +};
I think this map can be put into `zenoh_config.cpp`.  That will have the big benefit of it not being included with every compilation unit.

2024-02-28 13:25 UTC, Yadunund commented on README.md
> +`rmw_zenoh` relies on separate configurations files to configure the Zenoh `router` and `session` respectively. For more information on the topology of Zenoh adopted in `rmw_zenoh`, please see [Desig
I assume those terms will be clarified in the design document once your PR lands! Hence the link here to refer to that document

2024-02-28 13:35 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/zenoh_config.hpp
> +};
https://github.com/ros2/rmw_zenoh/pull/119/commits/2594ddb2228ba91a1279036b349004320f13aef4

2024-02-28 13:36 UTC, Yadunund commented on README.md
> +`rmw_zenoh` relies on separate configurations files to configure the Zenoh `router` and `session` respectively. For more information on the topology of Zenoh adopted in `rmw_zenoh`, please see [Desig
https://github.com/ros2/rmw_zenoh/pull/119/commits/dbc20c07e7699a14b5a097af11026379a47d3a96

2024-02-28 21:50 UTC, clalancette approved these changes

2024-02-28 21:51 UTC, merged