Updated zenoh-c to latest commit
osrf/rmw_zenoh pull request #164
Opened 2024-04-26 09:24 UTC by imstevenpmwork

Hi @Yadunund!
We're submitting this PR to ensure we use the latest zenoh-c commit before proceeding with our planned testing

2024-04-26 10:12 UTC, Yadunund requested changes
Could you also update the comment above the with PR # associated with this commit hash?

2024-04-27 04:03 UTC, Yadunund reviewed
Sorry minor nitpick.

2024-04-27 04:03 UTC, Yadunund commented on zenoh_c_vendor/CMakeLists.txt
> +# Set VCS_VERSION to include latest changes from zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/340
```suggestion
# Set VCS_VERSION to include latest changes from zenoh-c https://github.com/eclipse-zenoh/zenoh-c/pull/340.
```

2024-04-29 12:23 UTC, clalancette commented
I think I'm a little confused by this PR.  As far as I understood, if we bump to the latest `zenoh-c`, then some of our tests stop working.  We are still debugging that.  Am I misunderstanding, or did we solve that particular issue?

2024-04-29 12:39 UTC, imstevenpmwork commented
Hello @clalancette! This pull request targets the branch to evaluate rmw with Tokio zenoh-c. Although the current hash already corresponds to Tokio zenoh-c, it's a few weeks outdated. Hence, we believe it's prudent to update this branch to the latest Tokio zenoh-c version and rerun the tests to assess any potential improvements or regressions.

2024-05-07 21:19 UTC, Yadunund approved these changes
LGTM.

2024-05-07 21:19 UTC, merged