print router id on startup
osrf/rmw_zenoh pull request #189
Opened 2024-06-01 19:33 UTC by berndpfrommer

Minimal PR related to #188 
This was enough for me to realize that it would take too long to ramp up (learning the basics of rust, loaning etc) to do a better job here. Pulling in the liveliness utils to print out the router id is ugly as well (but still beats code replication).
I agree with @Yadunund that having the router ids of connected routers logged would be much better, but this is the best I can do in a limited amount of time. Please close if you plan on doing it right in the near future.
Your work on rmw_zenoh is much appreciated.

2024-06-02 18:18 UTC, Yadunund requested changes
Thanks a lot for this addition. I think it's the best we can do for now until the zenoh-c API allows one to register a callback that will trigger anytime a peer connects. For now there is [z_info_peers_zid](https://zenoh-c.readthedocs.io/en/0.11.0.2/api.html#c.z_info_peers_zid) but I believe it's a blocking call and does a check for peers at the time of invocation and not throughout the life of the session.

Left a minor suggestion to consider but LGTM otherwise.

2024-06-02 18:18 UTC, Yadunund commented on rmw_zenoh_cpp/src/zenohd/main.cpp
> +    "router id: %s\n",
```suggestion
    "Started Zenoh router with id: %s\n",
```

2024-06-03 09:27 UTC, JEnoch commented
Right, [`z_info_peers_zid()`](https://zenoh-c.readthedocs.io/en/0.11.0.2/api.html#c.z_info_peers_zid) returns the connected peers' ids at the time of call. You could call it periodically to log changes, but that requires to maintain a state and compare at each call.

An alternative is to activate Zenoh logs via the `RUST_LOG` environment variable, that could be set via an option before Session creation in `main.cpp`:
- `RUST_LOG=zenoh=info` for Session initialisation logs (i.e. id and listening endpoints)
- `RUST_LOG=zenoh=info,zenoh_transport=debug` to add connectivity events logging

Side note: reviewing this PR I saw that [`rmw_zenoh_cpp::liveliness::zid_to_str`](https://github.com/ros2/rmw_zenoh/blob/60b131ea969cc9711e08efd9e44e7fef6485d96e/rmw_zenoh_cpp/src/detail/liveliness_utils.cpp#L222) returns a hexadecimal string assuming `zid` is a big endian u128. Actually in Zenoh it's by convention a little endian u128. 
https://github.com/ros2/rmw_zenoh/pull/190 fixes this.

2024-06-03 17:28 UTC, Yadunund commented
Thanks for the information @JEnoch! 

> An alternative is to activate Zenoh logs via the RUST_LOG environment variable, that could be set via an option before Session creation in main.cpp:
RUST_LOG=zenoh=info for Session initialisation logs (i.e. id and listening endpoints)
RUST_LOG=zenoh=info,zenoh_transport=debug to add connectivity events logging

^ I think it's definitely worth adding these to the README for users who want more details.

2024-06-04 13:54 UTC, JEnoch commented
Done via https://github.com/ros2/rmw_zenoh/pull/191

@Yadunund  do you think it's good enough, or shall we add to the router a `--debug` option that automatically set `RUST_LOG` in main.cpp (if not already defined) ?
Or better, a cumulative `-v` option setting `RUST_LOG` to different values ?

2024-06-04 15:33 UTC, berndpfrommer commented
I think adding the -v option would be a good idea. The additional documentation in #191 is also most welcome.
I'd be happy to see this PR closed as obsolete.

2024-06-04 15:40 UTC, Yadunund commented
Adding the `-v` flag as highlighted above sounds great. I'm still good with merging this PR in the meanwhile.

2024-06-06 08:15 UTC, JEnoch commented
#197 adds the `-v` to the router.
I think it's still worth merging this PR which prints the router id without `-v`.
Using `-v` will also print it, but along other Zenoh startup logs (listening endpoints).

2024-06-06 18:38 UTC, Yadunund approved these changes

2024-06-06 20:04 UTC, merged