Add unit tests to CI
osrf/rmw_zenoh pull request #271
Opened 2024-08-27 11:32 UTC by CihatAltiparmak

2024-08-28 20:29 UTC, CihatAltiparmak commented
Hello @Yadunund ,

I've made some work to integrate system tests like `test_rclcpp` . But i have a bunch of question.

1. While running `colcon test --packages-select test_rclcpp` inside `rclcpp_integration.test.py` file, we have to set the current working directory of subprocess as workspace directory. I've solved by using launch arguments. I'm ready to hear some better ideas from you.
2. I couldn't add some packages like `test_rclcpp`, `launch_ros` to package.xml due to the fact that CI crash in command `colcon list --paths-only --packages-up-to rmw_zenoh_cpp zenoh_c_vendor` by throwing out `[1.821s] ERROR:colcon:colcon list: Unable to order packages topologically:` Do you have any idea?
I'm ready to review.

2024-08-29 08:09 UTC, ahcorde commented
> Hello @Yadunund ,
> 
> I've made some work to integrate system tests like `test_rclcpp` . But i have a bunch of question.
> 
> 1. While running `colcon test --packages-select test_rclcpp` inside `rclcpp_integration.test.py` file, we have to set the current working directory of subprocess as workspace directory. Otherwise colcon cannot find the workspace automatically. I've solved by using [launch arguments](https://github.com/CihatAltiparmak/rmw_zenoh/blob/dbccd7c074c916df872bf9500cd1a27cb74204fb/rmw_zenoh_cpp/test/rclcpp_integration.test.py#L38-L39). I'm ready to hear some better ideas from you.
> 2. I couldn't add some packages like `test_rclcpp`, `launch_ros` to package.xml due to the fact that CI fails in command `colcon list --paths-only --packages-up-to rmw_zenoh_cpp zenoh_c_vendor` by throwing out `[1.821s] ERROR:colcon:colcon list: Unable to order packages topologically:` Do you have any idea?
> 3. This time CI takes ~30 minutes for rolling source build and tests. I am yet to be able to decrease CI time. Are there some alternatives like `osrf/ros2::nightly` you know?
> 4. Should we add tests for `jazzy` and `iron`?
> 
> I'm ready to get some review.

Related to question:

2. I assume this is happening when using debs, `test_rclcpp` should not be available in the workspace that's why you see this error.

3.  Compiling up to `test_rclcpp` requires to compile many packages and the resources of the workers are not high. I think it's a resonable time. Using `osrf/ros2:nighly` will require to release a package to get the changes, while compiling from source it's just when we merge PRs. I think we should keep this behaviour. What do you think @Yadunund  ?

4. Yes, we should do the same with `jazzy` and `iron`. We might include some behavioral changes and we should be able to detect them

2024-09-05 06:38 UTC, CihatAltiparmak commented
Yeah you can ignore first qustion in https://github.com/ros2/rmw_zenoh/pull/271#issuecomment-2316195584 . More quetions:

1. Do you want to run test in only source builds, or you also want to run tests for binary builds ? 
2. Which test packages do you wanna run (`test_rclcpp`, `rcl`, `test_communication` and so on)?
3. Which files should be uploaded via upload artifact?

2024-09-09 18:52 UTC, Yadunund commented
Hi @CihatAltiparmak,

Sorry for the delay in my review.

> Do you want to run test in only source builds, or you also want to run tests for binary builds ?

We need to build `system_tests` from source as the binaries are not available. Since we already have a job that builds Rolling from source, we can just run the tests in the same workflow.

I wonder if we should not run the source job on pull request. Instead we can have it run nightly. We can add a Rolling binary job to the on pull request workflow.

> Which test packages do you wanna run (test_rclcpp, rcl, test_communication and so on)?

imo  `test_rclcpp` and `test_communication` would be good ones to run (we should include the `-DSKIP_MULTI_RMW_TESTS=On` cmake arg to the build command) but there is a known issue there https://github.com/ros2/rmw_zenoh/issues/275

> Which files should be uploaded via upload artifact?

`colcon test` should generate a test artifact (.gtest.xml) which you can find in the logs.

2024-09-10 01:04 UTC, CihatAltiparmak commented
> Hi @CihatAltiparmak,
> 
> Sorry for the delay in my review.
> 
> > Do you want to run test in only source builds, or you also want to run tests for binary builds ?
> 
> We need to build `system_tests` from source as the binaries are not available. Since we already have a job that builds Rolling from source, we can just run the tests in the same workflow.
> 
> I wonder if we should not run the source job on pull request. Instead we can have it run nightly. We can add a Rolling binary job to the on pull request workflow.
> 
> > Which test packages do you wanna run (test_rclcpp, rcl, test_communication and so on)?
> 
> imo `test_rclcpp` and `test_communication` would be good ones to run (we should include the `-DSKIP_MULTI_RMW_TESTS=On` cmake arg to the build command) but there is a known issue there #275
> 
> > Which files should be uploaded via upload artifact?
> 
> `colcon test` should generate a test artifact (.gtest.xml) which you can find in the logs.

Don't worry.  At the moment, we can add only binary builds to matrix when `github.event_name` is not scheduled. I've also added other suggestions like `-DSKIP_MULTI_RMW_TESTS=On` . The `selected_system_tests` arg can be passed to `rmw_zenoh_integration.test.py` It's okay for review after i pass the `env.RMW_MIDDLEWARE_TEST_PACKAGES` to `selected_system_tests`

2024-09-18 17:03 UTC, CihatAltiparmak commented
Hello @Yadunund , would you take a look at latest changes here? In latest version of this PR, we can run system test by giving argument to launch file and then load artifacts for each ros distro. Don't merge at the moment but it's ready. 

https://github.com/CihatAltiparmak/rmw_zenoh/blob/c326da645f83f859e0b723a26bcca41ccbcf29b8/.github/workflows/build.yaml#L22

After testing source based builds, we can modify this contidion. I'm aware of this change and it's temporary.

2024-09-19 00:51 UTC, Yadunund commented
@CihatAltiparmak the changes here looks great to me!

2024-09-19 08:36 UTC, CihatAltiparmak commented
> @CihatAltiparmak the changes here looks great to me!

Cool, i'm leaving to you which systems tests it will be run.

2024-10-01 17:31 UTC, ahcorde requested changes
we should test: `rcl` `rcl_action`, `rcl_lifecycle`, `rclcpp`, `rclcpp_action`, `rclcpp_lifecycle`, `test_communication`, `test_qos`, `test_rclcpp`

@clalancette and @Yadunund any other package that we should include?

@CihatAltiparmak anyhow some tests at least in `rcl` should fail, do you know why tests are skipped ? I can see this message in the action `Skipping tests`

2024-10-01 17:39 UTC, clalancette commented
> @clalancette and @Yadunund any other package that we should include?

I'm honestly not sure whether we should do this at all.

The goal here is to integrate `rmw_zenoh` into the main [ros2.repos](https://github.com/ros2/ros2/blob/rolling/ros2.repos).  Once we do that, the nightly jobs on https://ci.ros2.org will automatically be building and testing `rmw_zenoh` overnight.  Is it worth it to *also* have this in a GitHub action?  I'm not sure.

2024-10-01 18:38 UTC, CihatAltiparmak commented
@ahcorde Could you show which tests are skipped so that i can investigate this issue easier? Seems you already have merged PR that skips `test_event` related tests : https://github.com/ros2/rcl/pull/1180 and i see that all of skipped tests are related to this PR. But i will also run rcl tests in my computer and i will give feedback asap. If you decide to add this CI, i will add your suggestions. You can also add it, `allow maintainers to edit` option is ON.

@clalancette 

> Once we do that, the nightly jobs on https://ci.ros2.org/ will automatically be building and testing rmw_zenoh overnight.

The default configuration of rmw_zenoh needs  zenoh router to run separately. So i implemented `rmw_zenoh_integration.test.py` as well. to only run `colcon test` command doesn't work for the default configuration of `rmw_zenoh`. If you don't think this CI is not necessary, it can be deleted `build.yaml` file completely. I don't know how  https://ci.ros2.org/ runs. Btw this changes are temporary as @Yadunund states [here](https://github.com/ros2/rmw_zenoh/pull/256#discussion_r1727829564).

Now i come up with new option: `workflow_call`. You add to your `ros2.repos` url and the branch you wanna test thanks to this option.

2025-04-05 22:11 UTC, Yadunund commented
@CihatAltiparmak thanks for your valuable efforts to run CI on `rmw_zenoh` during early stages of this project. We've since managed to get `rmw_zenoh` to run on nightly CI jobs on the official ROS 2 Buildfarm. So we can close this out. Again, thanks a lot for your help!

2025-04-05 22:11 UTC, closed without merging