Fix minor typo in code comment
osrf/rmw_zenoh pull request #302
Opened 2024-10-23 20:39 UTC by duringhof

Fixed just a minor typo in a code comment, no code changes.

2024-10-24 07:45 UTC, Yadunund requested changes
Thanks for the contribution!

2024-10-24 07:45 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_init.cpp
> +/// Initialize the middleware with the given options, and yielding a context.
```suggestion
/// Initialize the middleware with the given options, and yield a context.
```

2024-10-24 09:58 UTC, duringhof commented
I updated the PR with the proposed change.
Thanks!

2024-10-25 09:24 UTC, ahcorde approved these changes

2024-10-25 09:24 UTC, merged