refactor: wrap the zenoh session with a shared pointer
osrf/rmw_zenoh pull request #333
Opened 2024-12-06 15:29 UTC by YuanYuYuan

Closes https://github.com/ZettaScaleLabs/rmw_zenoh/issues/44.

2024-12-06 16:25 UTC, clalancette requested changes
I generally like the idea here, but I think we need to do some more work particularly in the `ClientData` class.  I've left a detailed proposal in there.

2024-12-06 16:25 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/rmw_client_data.cpp
> +  sess_ = context_impl->session();
This doesn't seem correct to me.  If there are multiple `send_request` in-flight at the same time, then we'll only take *one* additional reference for the whole class, instead of one per in-flight request.  Instead, I think we should probably take a reference per-outstanding-request.  To do that while using the current `zenoh-c`, I think we'll have to manually do some work here.  In particular, I have something like this in mind:

```
struct ClientDataWrapper
{
    ClientDataWrapper(std::shared_ptr<Session> sess, std::shared_ptr<ClientData> cd)
    : session(sess), client_data(cd)
    {
    }
    std::shared_ptr<Session> session;
    std::shared_ptr<ClientData> client_data;
};
```

And then right here we would do:

```
ClientDataWrapper * wrapper = new ClientDataWrapper(context_impl->session(), shared_from_this());
```

And then we'd pass the `wrapper` into the `z_closure` as the user_data:

```
  z_closure(&zn_closure_reply, client_data_handler, client_data_drop, wrapper);
```

And then in `client_data_handler`, we'd use the wrapper class:

```
void client_data_handler(z_loaned_reply_t * reply, void * data)
{
  auto wrapper = static_cast<ClientDataWrapper *>(data);
  if (wrapper == nullptr) {
    RMW_ZENOH_LOG_ERROR_NAMED(
      "rmw_zenoh_cpp",
      "Unable to obtain client_data_t from data in client_data_handler."
    );
    return;
  }
  if (wrapper->client_data->is_shutdown()) {
    return;
  }
  if (!z_reply_is_ok(reply)) {
    const z_loaned_reply_err_t * err = z_reply_err(reply);
    const z_loaned_bytes_t * err_payload = z_reply_err_payload(err);
    z_owned_string_t err_str;
    z_bytes_to_string(err_payload, &err_str);
    RMW_ZENOH_LOG_ERROR_NAMED(
      "rmw_zenoh_cpp",
      "z_reply_is_ok returned False for keyexpr %s. Reason: %.*s",
      wrapper->client_data->topic_info().topic_keyexpr_.c_str(),
      static_cast<int>(z_string_len(z_loan(err_str))),
      z_string_data(z_loan(err_str)));
    z_drop(z_move(err_str));
    return;
  }
  std::chrono::nanoseconds::rep received_timestamp =
    std::chrono::system_clock::now().time_since_epoch().count();
  wrapper->client_data->add_new_reply(
    std::make_unique<rmw_zenoh_cpp::ZenohReply>(reply, received_timestamp));
}
```

And then finally, when `client_data_drop` is called, we'd free the memory:

```
void client_data_drop(void * data)
{
  auto wrapper = static_cast<ClientDataWrapper *>(data);
  if (wrapper == nullptr) {
    RMW_ZENOH_LOG_ERROR_NAMED(
      "rmw_zenoh_cpp",
      "Unable to obtain client_data_t from data in client_data_drop."
    );
    delete wrapper;
  }
}
```

What do you think?

2024-12-06 16:25 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    // }
```suggestion
```

2024-12-09 11:08 UTC, ahcorde requested changes
These changes are already included in the zenoh_c to zenoh_cpp PR https://github.com/ros2/rmw_zenoh/pull/327/files#diff-124e1086db3e5f3edb76619bd65943a900a963ef671e014c817d3bf27d803908

2024-12-09 14:22 UTC, clalancette commented
> These changes are already included in the zenoh_c to zenoh_cpp PR https://github.com/ros2/rmw_zenoh/pull/327/files#diff-124e1086db3e5f3edb76619bd65943a900a963ef671e014c817d3bf27d803908

I do think we should get this one in first, and then go for the switch to zenoh-cpp.  That will allow us to concentrate on one thing at a time, and I think this one is largely ready to go (with my one big comment up above still to be addressed).

2024-12-09 15:27 UTC, YuanYuYuan commented
> > These changes are already included in the zenoh_c to zenoh_cpp PR https://github.com/ros2/rmw_zenoh/pull/327/files#diff-124e1086db3e5f3edb76619bd65943a900a963ef671e014c817d3bf27d803908
> 
> I do think we should get this one in first, and then go for the switch to zenoh-cpp. That will allow us to concentrate on one thing at a time, and I think this one is largely ready to go (with my one big comment up above still to be addressed).

Hi @clalancette, I'm trying to understand the underlying issue with the client and the request-in-flight. But I'm wondering why we must clone a session for each request. It seems to me either the callback or the `client_data_drop` doesn't utilize the session.

2024-12-09 15:32 UTC, clalancette commented
> Hi @clalancette, I'm trying to understand the underlying issue with the client and the request-in-flight. But I'm wondering why we must clone a session for each request. It seems to me either the callback or the `client_data_drop` doesn't utilize the session.

Doesn't `client_data_drop` implicitly use the session, by the fact that it being called by the internals of Zenoh?  If that is not the case, then indeed we do not need to hold onto this here.  But in that case, I think we would want to hold onto the session for the lifetime of `ClientData` (i.e. take the reference in the constructor).

2024-12-09 16:46 UTC, YuanYuYuan commented
> Doesn't `client_data_drop` implicitly use the session, by the fact that it being called by the internals of Zenoh? If that is not the case, then indeed we do not need to hold onto this here. But in that case, I think we would want to hold onto the session for the lifetime of `ClientData` (i.e. take the reference in the constructor).

1. The `client_data_drop` is part of the closure. It doesn't really depend on a zenoh session but a zenoh runtime which is global and internal.
2. But whether the callback is triggered or not makes a difference. I ran some quick tests and discovered that in the recent zenoh version, a get request sent to a remote queryable won't trigger the callback if the get session is closed between the time the queryable receives the request and sends back the reply. The question is do we want to make sure each reply is handled even after the session is closed? If the answer is yes, then we need to clone the session for every request. Otherwise, we don't.
3. We recently introduced the `Querier`, which works like a `session.put` vs `publisher`. This means we can keep the `Querier` rather than a `session` as we do for the other rmw data in the future.

2024-12-09 17:25 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    // }
Thanks. Addressed in https://github.com/ros2/rmw_zenoh/pull/333/commits/0c27cabbec1d3646791f2998b3d4e17074a81cb5

2024-12-09 18:10 UTC, clalancette commented
> * But whether the callback is triggered or not makes a difference. I ran some quick tests and discovered that in the recent zenoh version, a get request sent to a remote queryable won't trigger the callback if the get session is closed between the time the queryable receives the request and sends back the reply. The question is do we want to make sure each reply is handled even after the session is closed? If the answer is yes, then we need to clone the session for every request. Otherwise, we don't.

No, I don't think we need to handle the reply after the session is closed.  In our case, the session being closed is the result of the context being shutdown, and after that point nothing in the higher layers can handle anything new anyway.

OK, so in that case, I'm going to withdraw my previous comment about fixing it (though I will open a separate PR doing that for the `ClientData`, which does need to be kept alive).  I'll put a different comment about possibly moving the Session reference count elsewhere.

2024-12-09 18:10 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/rmw_client_data.cpp
> +  sess_ = context_impl->session();
As discussed in https://github.com/ros2/rmw_zenoh/pull/333#issuecomment-2528971056 , we don't necessarily need this.  So resolving this particular conversation.

2024-12-09 18:13 UTC, clalancette requested changes
One more change to make, then I think this is good to go.

2024-12-09 18:13 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/rmw_client_data.cpp
> +  sess_ = context_impl->session();
I don't think we need this, right?  Because we are holding onto the session while this `ClientData` is alive, this is an unnecessary additional reference count, and I think it is enough to just keep this in the constructor.

2024-12-10 07:31 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_client_data.cpp
> +  sess_ = context_impl->session();
Thanks. It's misplaced. Resolved in https://github.com/ros2/rmw_zenoh/pull/333/commits/416f4303c1ef9ed739bb6adcec961b760829ad23

2024-12-10 17:13 UTC, YuanYuYuan commented
Rebase it against the latest rolling.

2024-12-10 19:18 UTC, clalancette approved these changes

2024-12-10 19:18 UTC, merged