Recycle serialization buffers on transmission.
osrf/rmw_zenoh pull request #342
Opened 2024-12-16 17:34 UTC by fuzzypixelz

Adds a LIFO buffer pool in the context to reuse buffers allocated on serialization. The aim is not (only) to avoid the overhead of dynamic allocation but rather to enhance the cache locality of serialization buffers.

2024-12-16 17:44 UTC, fuzzypixelz commented
The aim of this pull request is to fix high latency for relatively large topics (e.g. 1 MB `tagus`) in the single-process iRobot benchmark with `--ipc off`. Results were obtained on an **Ubuntu 24.04.1 LTS** machine with an **Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz**.

# dd82e84
| node | topic | size_b | mean_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 3016 | 2512 | 5705 |
| geneva | tagus | 1000000 | 3513 | 2997 | 6457 |
| mandalay | tagus | 1000000 | 2678 | 2214 | 5233 |

# 16df6fe
| node | topic | size_b | mean_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 1947 | 1476 | 2788 |
| geneva | tagus | 1000000 | 2200 | 1667 | 3063 |
| mandalay | tagus | 1000000 | 1603 | 1225 | 1997 |

# 16df6fe + a4be550
| node | topic | size_b | mean_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 393 | 257 | 1301 |
| geneva | tagus | 1000000 | 657 | 438 | 1701 |
| mandalay | tagus | 1000000 | 108 | 68 | 650 |

2024-12-17 21:41 UTC, clalancette commented
All right, now that we've merged in #327 , we can consider this one.  Please rebase this onto the latest, then we can do a full review of it.  Until then, I'll mark it as a draft.

2024-12-19 11:44 UTC, ahcorde requested changes
There are also many changes unrelated with the goal of this PR

2024-12-19 11:44 UTC, ahcorde commented on rmw_zenoh_cpp/src/detail/buffer_pool.hpp
> +    size_t size;
include `<cstddef>`

2024-12-19 14:52 UTC, fuzzypixelz commented
> There are also many changes unrelated with the goal of this PR

There was a formatting error from my IDE. I've restored the files and manually re-applied the patches.

2025-01-02 21:29 UTC, clalancette requested changes
Besides the comments inline, do you have any updated performance numbers here?

2025-01-02 21:29 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +      }
There is a corner case in error-handling here, where if there was enough size in the pool, but `allocator.reallocate` failed, we would have increased the pool size without actually allocating the memory.  To be fair, in this situation it is probably the case that there is going to be a crash soon, but we can still handle this a bit nicer:

```suggestion
    if (buffer.size < size) {
      size_t size_diff = size - buffer.size;
      if (size_ + size_diff > max_size_) {
        return {};
      }
      uint8_t * data = static_cast<uint8_t *>(allocator.reallocate(
          buffer.data, size, allocator.state));
      if (data == nullptr) {
        return {};
      }
      size_ += size_diff;
      buffer.data = data;
      buffer.size = size;
```

2025-01-02 21:29 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +  const char * error_str = rcutils_get_env("RMW_ZENOH_BUFFER_POOL_MAX_SIZE_BYTES", &env_value);
Can you please put a note somewhere in https://github.com/ros2/rmw_zenoh/blob/rolling/docs/design.md explaining what this environment variable is and what it does?  I know that document is out-of-date w.r.t. the changes to zenoh-cpp, but I still think it has value to have this documented somewhere.

2025-01-02 21:29 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +  rcutils_allocator_t allocator = rcutils_get_default_allocator();
This is going to require some additional plumbing, but I think we should respect the allocator passed in via the `options` during `rmw_init`.  To get to that, we'll have to change the constructor of `rmw_context_impl_s` to pass that into the `BufferPool` constructor, and then we can store the pointer in this class and use it as necessary.

2025-01-03 08:39 UTC, fuzzypixelz commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +  rcutils_allocator_t allocator = rcutils_get_default_allocator();
I don't think we should be using the allocator passed in `rmw_init_options_s` for all allocation in the RMW.

1. According to the [documentation](https://docs.ros.org/en/rolling/p/rmw/generated/structrmw__init__options__s.html#exhale-struct-structrmw-init-options-s), `rmw_init_options_s::allocator` is "[The] allocator used during internal allocation of init options, if needed.". So by the same `rmw_init` is called, we have no business allocating through it.
2. Other RMW implementations don't use `rmw_init_options_s::allocator` either. Instead they use [`rcutils_get_default_allocator`](https://github.com/ros2/rmw_fastrtps/blob/508ad9dd2ce05cb831ba00e9784c5f334101174c/rmw_fastrtps_cpp/src/subscription.cpp#L443) and [`rmw_allocate`](https://github.com/ros2/rmw_cyclonedds/blob/854b89d5b03110e63d778908c35d55d01d8495d1/rmw_cyclonedds_cpp/src/rmw_node.cpp#L4141).
3. The only place where this allocator seems useful is in [`rmw_init_options_fini`](https://github.com/ros2/rmw_fastrtps/blob/508ad9dd2ce05cb831ba00e9784c5f334101174c/rmw_fastrtps_shared_cpp/src/rmw_init.cpp#L100-L125).

We also allocate many `std::vector` and `std::string` without the default allocator anyway, which seems wrong.

I can make a subsequent pull request addressing this issue.

2025-01-03 14:19 UTC, fuzzypixelz commented
> Besides the comments inline, do you have any updated performance numbers here?

The following results were obtained using the Mont Blanc topology (with a 1 MiB `tagus` topic size) on an **Ubuntu 24.04.1 LTS** machine with an **12th Gen Intel(R) Core(TM) i5-1240P** (different machine).

# 57a6b4b8f07b86d9ab140b9e0c204055d885c5e2
| node | topic | size_b | mean_us | sd_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 839 | 255 | 235 | 1227 |
| geneva | tagus | 1000000 | 1053 | 285 | 327 | 1490 |
| mandalay | tagus | 1000000 | 643 | 252 | 121 | 1011 |

# 8ba527851248f697b082002f60d434658c1d440b
| node | topic | size_b | mean_us | sd_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 545 | 192 | 173 | 1091 |
| geneva | tagus | 1000000 | 702 | 193 | 253 | 1326 |
| mandalay | tagus | 1000000 | 342 | 189 | 86 | 771 |

# cebb972b39f3daf06a2be7be95952cab96156df2
| node | topic | size_b | mean_us | sd_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 368 | 162 | 87 | 879 |
| geneva | tagus | 1000000 | 522 | 162 | 127 | 1071 |
| mandalay | tagus | 1000000 | 188 | 159 | 38 | 646 |

# cebb972b39f3daf06a2be7be95952cab96156df2 + 8ba527851248f697b082002f60d434658c1d440b
| node | topic | size_b | mean_us | sd_us | min_us | max_us |
|--------|--------|--------|--------|--------|--------|--------|
| ponce | tagus | 1000000 | 224 | 31 | 60 | 313 |
| geneva | tagus | 1000000 | 379 | 52 | 99 | 528 |
| mandalay | tagus | 1000000 | 58 | 10 | 20 | 87 |

2025-01-21 13:43 UTC, clalancette requested changes

2025-01-21 13:43 UTC, clalancette commented on docs/design.md
> +communication, or upon being consumed by subscriptions in intra-process communication, etc.
```suggestion
The RMW recycles serialization buffers on transmission using a buffer pool with bounded memory
usage.
These buffers are returned to the pool - without being deallocated - once they cross the
network boundary in host-to-host communication, or after transmission in inter-process
communication, or upon being consumed by subscriptions in intra-process communication, etc. 
```

2025-01-21 13:43 UTC, clalancette commented on docs/design.md
> +allocator and moved to Zenoh; no recyling is performed in this case to prevent the buffer pool from
```suggestion
allocator and moved to Zenoh; no recycling is performed in this case to prevent the buffer pool from
```

2025-01-21 13:43 UTC, clalancette commented on docs/design.md
> +size of a typical modern CPU.
```suggestion
The default value of `RMW_ZENOH_BUFFER_POOL_MAX_SIZE_BYTES` is 16MB; this value was chosen since it is roughly the size of the cache in a modern CPU.
```

2025-01-21 13:43 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +    RMW_ZENOH_LOG_ERROR_NAMED(
This is somewhat pedantic, but I think this should be a WARN since we are continuing on anyway.

2025-01-21 13:43 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +  rcutils_allocator_t allocator = rcutils_get_default_allocator();
The thing with the allocators is that always using `rcutils_get_default_allocator` is useless.  The default allocator is just `malloc`, `realloc`, `free`, etc.  So you may as well use those.

Memory allocation is a tricky subject here.  The original goal of the `rcutils_allocator` was to make it so that consumers of the RMW API could add in an allocator that is *not* the default (like a pool allocator).  Early on in `rmw_zenoh` development, we were very careful to use the passed-in allocator everywhere.  As we've switched to C++ in more places, that has somewhat fallen by the wayside.

@Yadunund What's your thinking here?  Should we give up on the `rcutils_allocator` and just use C++ builtins everywhere?  Or should we move in the direction of trying to honor `rcutils_allocator` as much as we can?

2025-01-29 17:35 UTC, Yadunund requested changes
Overall this looks good. I've left some feedback to re-structure the code a bit.

2025-01-29 17:35 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.hpp
> +  rmw_zenoh_cpp::BufferPool serialization_buffer_pool;
Move into `Data` impl and add public method to class to return a `shared_ptr<rmf_zenoh_cpp::BufferPool>`

2025-01-29 17:35 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/buffer_pool.hpp
> +class BufferPool
I'd prefer moving this into `zenoh_utils.hpp`

2025-01-29 19:05 UTC, fuzzypixelz commented
@clalancette @Yadunund The numbers I've shown are for single-process (session-local) communication. I would like to investigate the impact of this pull request on multi-process communication on the same host as well, to make sure we're not degrading performance in that case.

Once that's done, I will post numbers and address your remaining review comments.

2025-01-30 15:52 UTC, fuzzypixelz commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +  rcutils_allocator_t allocator = rcutils_get_default_allocator();
I was wrongly under the impression that `rcutils_get_default_allocator `could be overridden. I don't mind doing the plumbing if we decide to use the `rcutils_allocator` passed in `rmw_init`.

I also think that the RMW documentation is misleading and should be updated.

2025-02-07 00:54 UTC, Yadunund commented
> @clalancette @Yadunund The numbers I've shown are for single-process (session-local) communication. I would like to investigate the impact of this pull request on multi-process communication on the same host as well, to make sure we're not degrading performance in that case.
> 
> Once that's done, I will post numbers and address your remaining review comments.

@fuzzypixelz any update on performance metrics after the recent set of changes? Is this ready for another review?

2025-02-07 16:34 UTC, fuzzypixelz commented
@clalancette @Yadunund Here are the benchmarking results. I have used the iRobot benchmark [here](https://github.com/irobot-ros/ros2-performance/compare/rolling...ZettaScaleLabs:ros2-performance:quartiles) in single-process and multi-process modes, using the Mont Blanc topology with IPC disabled (only relevant for single-process mode). I used four benchmarking machines with varying specs to make sure we perform properly on both low-end and high-end devices.

# Host 1
## System information
- **CPU**: AMD EPYC 7502 32-Core Processor
- **MEM**: 512G
## Single-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/428e919c-187c-456f-8d28-d48c3952d35d)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/bea2c9fb-bfaa-4c63-92dd-5753c2143f74)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/24fffc3d-dc0d-423b-b695-1d30ee170879)

## Multi-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/ffe68ce5-1ea9-4883-b59b-40c5ee69ca8c)


### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/e76b3096-5853-4e42-b2c5-4eac20f4c683)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/5e55527a-4527-4cc9-868e-484d951c4a9e)

# Host 2
## System information
- **CPU**: 12th Gen Intel(R) Core(TM) i5-1240P
- **MEM**: 16G
## Single-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/39a1986d-ce39-4f65-9fc2-be8a22386c90)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/f09cee49-a5d9-449a-b5c8-d12ea92495c9)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/1cbe0cd9-6e8d-4a26-b78c-c03c2624b019)

## Multi-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/756a01f1-846e-4b4e-a19f-b89e72b87a38)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/9dcfa43d-54e0-4145-a83a-917f76f1f0fc)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/65ef2a15-914e-4d2a-91a9-16aec9a937d0)

# Host 3
## System information
- **CPU**: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
- **MEM**: 8G
## Single-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/f7c5fab5-953c-4ebd-9ffc-49d937f71c7c)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/7c5bab30-0318-4477-85ee-57f49938768e)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/16b19c0b-3349-4258-8604-7cb5eb913833)

## Multi-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/708bbf01-879e-4f8a-ad30-d336bf9252b2)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/268e6b16-da83-4302-b5a3-08c70088a1ae)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/28f97429-227b-49e1-a01e-f1974aaca318)

# Host 4
- **CPU**: ARM Cortex-A76
- **MEM**: 8G
## Single-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/b060d5cc-2dad-4bf6-b302-c81a4144bb36)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/e7dfd437-2e66-49c1-a16e-bfb43e64bb5e)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/cfbfc7e3-efb7-4789-ab81-510dab8ffbe5)

## Multi-process
### Q2
![plot_q2_us_combined](https://github.com/user-attachments/assets/de66a48f-1263-40c4-8d54-e31e00798ba6)

### Q3
![plot_q3_us_combined](https://github.com/user-attachments/assets/0950bc43-f73c-4b2f-8e65-ef26c3197fdd)

### Mean
![plot_mean_us_combined](https://github.com/user-attachments/assets/642a7768-080e-4ed2-9263-1a71d219247c)

2025-02-07 16:38 UTC, fuzzypixelz commented
The above comment turned out too long, I should probably use collapsed sections. In any case, my conclusion is that this pull request significantly improves latency in intra-process communication for relatively large topics, and apparently doesn't have an impact on inter-process communication.

2025-02-12 01:43 UTC, Yadunund commented
@fuzzypixelz thanks a lot for the detailed study! I'll take a closer look later this week.

2025-02-13 07:53 UTC, Yadunund requested changes

2025-02-13 07:53 UTC, Yadunund commented on docs/design.md
> +`RMW_ZENOH_BUFFER_POOL_MAX_SIZE_BYTES`, serialization buffers are allocated using the system
What happens if we set this to `0`?

2025-02-13 07:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/buffer_pool.hpp
> +// Copyright 2024 Open Source Robotics Foundation, Inc.
```suggestion
// Copyright 2025 Open Source Robotics Foundation, Inc.
```

2025-02-13 07:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +// Copyright 2024 Open Source Robotics Foundation, Inc.
```suggestion
// Copyright 2025 Open Source Robotics Foundation, Inc.
```

2025-02-13 07:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/buffer_pool.hpp
> +class BufferPool
@fuzzypixelz this comment is still not addressed.

2025-02-13 07:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +    RMW_ZENOH_LOG_ERROR_NAMED(
@fuzzypixelz can you address this comment?

2025-02-13 07:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/buffer_pool.cpp
> +  rcutils_allocator_t allocator = rcutils_get_default_allocator();
Personally i'm of the opinion that we can give up on `rcutils_allocator` especially if we always get the default allocator.. We have not been very consistent in some parts of the codebase and with any new code we write, I'd say we can sidestep it.

2025-02-13 07:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.hpp
> +  rmw_zenoh_cpp::BufferPool serialization_buffer_pool;
@fuzzypixelz this comment as well.

2025-02-20 15:19 UTC, fuzzypixelz commented on docs/design.md
> +`RMW_ZENOH_BUFFER_POOL_MAX_SIZE_BYTES`, serialization buffers are allocated using the system
The the max buffer pool size is 0 and we never allocate through it.

2025-02-20 17:09 UTC, fuzzypixelz commented
@Yadunund This should be ready to merge.

2025-03-12 15:11 UTC, ahcorde requested changes
I merge this branch with `rolling` and if you run

```bash
colcon test --merge-install --event-handlers console_direct+ --packages-select rc
```

you will see some new failures

2025-03-14 00:37 UTC, Yadunund commented
@fuzzypixelz let's revisit this after the kilted freeze.

2025-07-18 09:31 UTC, YuanYuYuan commented
Rebase onto the latest rolling.

2025-07-18 09:53 UTC, YuanYuYuan commented
Pulls: ros2/rmw_zenoh#342
Gist: https://gist.githubusercontent.com/YuanYuYuan/836dc36cf4adf8cf771afdcff2bb962f/raw/653c26346ad735a3035640d9868babe5286e90fc/ros2.repos
BUILD args: --packages-above-and-dependencies rmw_zenoh_cpp
TEST args: --packages-above rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16530
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24372)](http://ci.ros2.org/job/ci_linux/24372/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18436)](http://ci.ros2.org/job/ci_linux-aarch64/18436/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3810)](http://ci.ros2.org/job/ci_linux-rhel/3810/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24934)](http://ci.ros2.org/job/ci_windows/24934/)

2025-07-21 09:35 UTC, YuanYuYuan commented
Pulls: ros2/rmw_zenoh#342
Gist: https://gist.githubusercontent.com/YuanYuYuan/23b4f2fc1014d3b3bde49389fb12d244/raw/653c26346ad735a3035640d9868babe5286e90fc/ros2.repos
BUILD args: --packages-above-and-dependencies rmw_zenoh_cpp
TEST args: --packages-above rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16545
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24387)](http://ci.ros2.org/job/ci_linux/24387/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18463)](http://ci.ros2.org/job/ci_linux-aarch64/18463/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3832)](http://ci.ros2.org/job/ci_linux-rhel/3832/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=24949)](http://ci.ros2.org/job/ci_windows/24949/)

2025-07-22 03:38 UTC, YuanYuYuan commented
> @fuzzypixelz let's revisit this after the kilted freeze.

I've rebased this onto the latest rolling version, and the CI appeared to be good. Could you please review this again?

2025-07-22 20:58 UTC, Yadunund commented
@YuanYuYuan thanks for updating the PR. I will take a look towards the end of my week.

2025-07-28 01:09 UTC, Yadunund requested changes
This is looking great. A couple of minor suggestions to consider.

2025-07-28 01:09 UTC, Yadunund commented on docs/design.md
> +### `RMW_ZENOH_BUFFER_POOL_MAX_SIZE_BYTES`
Add this under the Configuration section of the README instead since that section includes other environment variables one can configure? Then we can move all the configuration contents in the `README.md` to `docs/design.md` as part of https://github.com/ros2/rmw_zenoh/pull/395/files

2025-07-28 01:09 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +  rmw_context_impl_s *context_impl = static_cast<rmw_context_impl_s *>(rmw_node_->data);
Check for nullptr.
```suggestion
  rmw_context_impl_s * context_impl =
    static_cast<rmw_context_impl_s *>(rmw_node->data);
  if (context_impl == nullptr) {
    RMW_SET_ERROR_MSG("Unable to cast rmw_node->data into rmw_context_impl_s.");
    return RMW_RET_ERROR;
  }
```

2025-07-28 01:09 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/zenoh_utils.hpp
> +  struct Buffer
Since the internal implementation of `BufferPool` is managing the memory of the `Buffer` using the default allocator, I'd like to propose tightening up this API to ensure that only `BufferPool` members are able to construct instances of `Buffer`. It's very unlikely some other part of the code will create a `Buffer` object using a different allocator and pass it back to the `BufferPool` via `deallocate()`, but it doesn't hurt to be safe. 

What do you think about: 
- Converting `Buffer` to a class.
- Moving the constructor of `Buffer` to `private` scope and declaring it as a `friend` of `BufferPool`. The `data` and `size` members can remain public.

2025-07-28 01:09 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/zenoh_utils.hpp
> +  Buffer allocate(size_t size);
To make it clear that allocation failed as opposed to relying on checking `serialization_buffer.data == nullptr` in `rmw_publisher_data.cpp`.
```suggestion
  std::optional<Buffer> allocate(size_t size);
```

2025-07-28 01:09 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/zenoh_utils.cpp
> +      size_t size_diff = size - buffer.size;
```suggestion
      const size_t size_diff = size - buffer.size;
```

2025-08-08 08:53 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/zenoh_utils.hpp
> +  Buffer allocate(size_t size);
Addressed in cefeedeacd53cc3d310bcd08605cd9fd4e3ca797

2025-08-08 08:53 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/zenoh_utils.cpp
> +      size_t size_diff = size - buffer.size;
Addressed in cefeedeacd53cc3d310bcd08605cd9fd4e3ca797.

2025-08-08 08:53 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/zenoh_utils.hpp
> +  struct Buffer
Addressed in cefeedeacd53cc3d310bcd08605cd9fd4e3ca797.

2025-08-08 08:56 UTC, YuanYuYuan commented on docs/design.md
> +### `RMW_ZENOH_BUFFER_POOL_MAX_SIZE_BYTES`
Addressed in cefeedeacd53cc3d310bcd08605cd9fd4e3ca797.

2025-08-18 16:03 UTC, Yadunund commented
@YuanYuYuan could you please resolve the conflicts?

2025-08-25 12:37 UTC, YuanYuYuan commented
> @YuanYuYuan could you please resolve the conflicts?

Hi @Yadunund, could you please review it again? Thanks!

2025-08-26 21:57 UTC, Yadunund approved these changes
LGTM! Thanks for iterating.

2025-08-27 08:10 UTC, ahcorde commented
Pulls: ros2/rmw_zenoh#342
Gist: https://gist.githubusercontent.com/ahcorde/2da2d094e2b9b5c27b54b71570f974c4/raw/653c26346ad735a3035640d9868babe5286e90fc/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw_zenoh_cpp
TEST args:  --packages-above rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16792
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24700)](http://ci.ros2.org/job/ci_linux/24700/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18725)](http://ci.ros2.org/job/ci_linux-aarch64/18725/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=4148)](http://ci.ros2.org/job/ci_linux-rhel/4148/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25218)](http://ci.ros2.org/job/ci_windows/25218/)

2025-08-27 08:29 UTC, ahcorde approved these changes

2025-09-01 10:44 UTC, YuanYuYuan commented
Pulls: ros2/rmw_zenoh#342
Gist: https://gist.githubusercontent.com/YuanYuYuan/d5f7fc7faa518e92a3518857e1f78d31/raw/653c26346ad735a3035640d9868babe5286e90fc/ros2.repos
BUILD args: --packages-above-and-dependencies rmw_zenoh_cpp
TEST args: --packages-above rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16817
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24727)](http://ci.ros2.org/job/ci_linux/24727/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18754)](http://ci.ros2.org/job/ci_linux-aarch64/18754/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=4176)](http://ci.ros2.org/job/ci_linux-rhel/4176/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25243)](http://ci.ros2.org/job/ci_windows/25243/)

2025-09-02 07:42 UTC, merged

2025-09-02 07:42 UTC, ahcorde commented
warning are unrelated. Merging!

2025-09-02 07:43 UTC, ahcorde commented
https://github.com/Mergifyio backport kilted jazzy humble