bump zenoh_c and zenoh_cpp versions
osrf/rmw_zenoh pull request #353
Opened 2024-12-20 11:42 UTC by ahcorde

Related with https://github.com/ros2/rmw_zenoh/issues/350

2024-12-20 11:48 UTC, Yadunund requested changes

2024-12-20 11:48 UTC, Yadunund commented on zenoh_cpp_vendor/CMakeLists.txt
>  # - https://github.com/eclipse-zenoh/zenoh-c/pull/620 (fix ze_querying_subscriber_get API to query newly discovered publishers)
Can we delete the comments above and replace it with a single comment referencing the PR that fixed the build issue? The old issues should be outdated now that we've upgraded to 1.0

2024-12-23 15:53 UTC, clalancette approved these changes

2024-12-23 15:54 UTC, merged

2025-01-02 01:19 UTC, Yadunund commented
@Mergifyio backport humble jazzy