Shared Memory on C++ API
osrf/rmw_zenoh pull request #363
Opened 2024-12-27 14:30 UTC by yellowhatter

SHM functionality implemented on C++ API

Transparently places ROS messages that are above configurable size threshold into shared-memory.

2024-12-27 20:39 UTC, ahcorde commented on rmw_zenoh_cpp/src/detail/shm_context.hpp
> +  size_t msgsize_threshold;
include `<cstddef>`

2024-12-27 20:39 UTC, ahcorde commented on rmw_zenoh_cpp/src/detail/shm_context.cpp
> +ShmContext::ShmContext(size_t alloc_size, size_t msgsize_threshold)
include `<cstddef>`

2025-01-06 15:31 UTC, yellowhatter commented on rmw_zenoh_cpp/src/detail/shm_context.hpp
> +  size_t msgsize_threshold;
fixed

2025-01-06 15:32 UTC, yellowhatter commented on rmw_zenoh_cpp/src/detail/shm_context.cpp
> +ShmContext::ShmContext(size_t alloc_size, size_t msgsize_threshold)
fixed in `shm_context.hpp`

2025-01-10 08:54 UTC, clalancette requested changes

2025-01-10 08:54 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.cpp
> +#ifdef RMW_ZENOH_BUILD_WITH_SHARED_MEMORY
I will say that I'm not a huge fan of wrapping this in a `#ifdef` this way.  When we release it on the buildfarm, we can only choose one define here, so we may as well just unconditionally add it.

In other words, if we think this feature is stable enough to use, we should just always build it in.  If it is not yet stable enough to use, then we shouldn't merge the PR until we are confident in it.

2025-01-10 08:54 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/zenoh_config.cpp
> +static const size_t zenoh_shm_alloc_size_default = 16 * 1024 * 1024;
What is the behavior of the shared-memory code if a message is published that is larger than this?  Given my comment above, I think that we should make it fall-back to the "regular" allocation path and not use shared-memory.

2025-01-10 09:08 UTC, yellowhatter commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.cpp
> +#ifdef RMW_ZENOH_BUILD_WITH_SHARED_MEMORY
This define is not about the stability but about binary size. SHM is relatively big subsystem of Zenoh with additional dependencies (and it will get even larger in the future). We have shared-memory feature conditionally compiled through the whole bunch of our projects: zenoh -> zenoh-c -> zenoh-cpp, so supporting this in zenoh_rmw makes sense for users who care about binary size. You can release RMW with `RMW_ZENOH_BUILD_WITH_SHARED_MEMORY=true` (which is `true` by default), but there still will be an option for users to make custom build without SHM.

2025-01-10 09:11 UTC, yellowhatter commented on rmw_zenoh_cpp/src/detail/zenoh_config.cpp
> +static const size_t zenoh_shm_alloc_size_default = 16 * 1024 * 1024;
Currently rmw_zenoh falls back to common allocation if for any reason the SHM allocation failed

2025-01-21 13:45 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.cpp
> +#ifdef RMW_ZENOH_BUILD_WITH_SHARED_MEMORY
The problem is that most of our users will have no ability to enable/disable this, since they will use the binary packages.  And in a typical ROS 2 installation, my opinion is that this is not going to be the biggest bit; rclcpp, for instance, will be far larger.  So I still feel like we should just unconditionally compile this in.

@Yadunund how do you feel about it?

2025-01-21 14:59 UTC, ruffsl commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.cpp
> +#ifdef RMW_ZENOH_BUILD_WITH_SHARED_MEMORY
Would this be for users who are building the stack from source via Yocto for embedded targets? As in, for memory constrained applications that only a respond one ROS node per device?

2025-03-07 07:04 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/rmw-zenoh-binaries-for-rolling-jazzy-and-humble/41395/26

2025-03-20 15:42 UTC, YuanYuYuan commented
@ahcorde, you can enable SHM using the setting below.

```
export ZENOH_SHM_MESSAGE_SIZE_THRESHOLD=1
export ZENOH_SHM_ENABLED=true
export ZENOH_CONFIG_OVERRIDE="transport/shared_memory/enabled=true" 
```

2025-03-25 06:30 UTC, YuanYuYuan commented
Update: The `ZENOH_SHM_ENABLED` environment variable has been removed (which was used for publishing messages within SHM buffers) and merged into the config option "transport/shared_memory/enabled=true" (which is used to determine receiving behavior).

2025-04-23 08:42 UTC, mcp-ats commented
Hi, what is the plan for Jazzy? Will this be backported to Jazzy?

I cannot try right now on rolling but I tried the following branch from Zetta:

https://github.com/ZettaScaleLabs/rmw_zenoh/commits/dev/1.0.0-cpp-shm-jazzy/

It works despite some complaints on the subscription side:

<details><summary>ros2 run image_tools showimage</summary>

```console
>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'failed to resolve symbol 'rmw_event_type_is_supported' in shared library '/home/mcp/ws_zenoh/install/rmw_zenoh_cpp/lib/librmw_zenoh_cpp.so', at ./src/functions.cpp:152'

with this new error message:

  'Expected lexeme type (19) not found, search ended at index 40, at ./src/rcl/lexer_lookahead.c:239'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
```
</details>

<details><summary>ros2 topic hz /image -w 200</summary>

```console
>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'failed to resolve symbol 'rmw_event_type_is_supported' in shared library '/home/mcp/ws_zenoh/install/rmw_zenoh_cpp/lib/librmw_zenoh_cpp.so', at ./src/functions.cpp:152'

with this new error message:

  'service's implementation is invalid, at ./src/rcl/service.c:427'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
```
</details>

I will try to use rolling as soon as I can!

2025-04-25 16:10 UTC, mcp-ats commented
Hey I tried with rolling and with this PR but I have some sporadic crashes at the beginning of the publisher, see below.

<details><summary>ros2 run image_tools cam2image --ros-args -p burger_mode:=true -p width:=1920 -p height:=1080 -p frequency:=50.0</summary>

```console
2025-04-25T16:08:24.657452Z  WARN Watchdog Confirmator ThreadId(03) zenoh_shm::watchdog::periodic_task: Some("Watchdog Confirmator"): error setting scheduling priority for thread: OS(1), will run with priority 48. This is not an hard error and it can be safely ignored under normal operating conditions. Though the SHM subsystem may experience some timeouts in case of an heavy congested system where this watchdog thread may not be scheduled at the required frequency.
2025-04-25T16:08:24.657463Z  WARN   Watchdog Validator ThreadId(04) zenoh_shm::watchdog::periodic_task: Some("Watchdog Validator"): error setting scheduling priority for thread: OS(1), will run with priority 48. This is not an hard error and it can be safely ignored under normal operating conditions. Though the SHM subsystem may experience some timeouts in case of an heavy congested system where this watchdog thread may not be scheduled at the required frequency.
[INFO] [1745597304.739037321] [cam2image]: Publishing image #1
[INFO] [1745597304.757779241] [cam2image]: Publishing image #2
[INFO] [1745597304.777845078] [cam2image]: Publishing image #3
[INFO] [1745597304.797739350] [cam2image]: Publishing image #4
[INFO] [1745597304.817716038] [cam2image]: Publishing image #5
[INFO] [1745597304.837761351] [cam2image]: Publishing image #6
[INFO] [1745597304.857756956] [cam2image]: Publishing image #7
[INFO] [1745597304.877738982] [cam2image]: Publishing image #8
[INFO] [1745597304.897754033] [cam2image]: Publishing image #9
[INFO] [1745597304.917714415] [cam2image]: Publishing image #10
thread '<unnamed>' panicked at library/std/src/time.rs:417:33:
overflow when adding duration to instant
stack backtrace:
   0:     0x77697b7ef1cc - std::backtrace_rs::backtrace::libunwind::trace::he991e66e5f22a1db
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x77697b7ef1cc - std::backtrace_rs::backtrace::trace_unsynchronized::h43f35a5576eecb13
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x77697b7ef1cc - std::sys_common::backtrace::_print_fmt::hf9c799a68b2477fc
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x77697b7ef1cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2d48dfeb5948660
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x77697b6acb80 - core::fmt::rt::Argument::fmt::h507ca91fbb1ef494
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/rt.rs:142:9
   5:     0x77697b6acb80 - core::fmt::write::h4d5f6025aa566322
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1120:17
   6:     0x77697b7e69a1 - std::io::Write::write_fmt::hc088b3c8cc6dcb9f
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1762:15
   7:     0x77697b7eef6e - std::sys_common::backtrace::_print::h231201f6cff8f56a
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x77697b7eef6e - std::sys_common::backtrace::print::h478d6be486f8cd2d
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x77697b80c640 - std::panicking::default_hook::{{closure}}::hf1c55106b4d45a90
  10:     0x77697b80d190 - std::panicking::default_hook::h7b29000c631cc719
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:292:9
  11:     0x77697b80d190 - std::panicking::rust_panic_with_hook::h2a988919dd121561
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:779:13
  12:     0x77697b7ef76c - std::panicking::begin_panic_handler::{{closure}}::h3a9eaa1d23ecf555
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:657:13
  13:     0x77697b7ef6c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h813561fdec15f700
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x77697b80c9c1 - rust_begin_unwind
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
  15:     0x77697b4c2cf4 - core::panicking::panic_fmt::hef0307862026e6f9
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
  16:     0x77697b4c3382 - core::panicking::panic_display::hed86ea0466f0a3dc
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:178:5
  17:     0x77697b4c3382 - core::panicking::panic_str::h1dc008f642ffb82c
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:152:5
  18:     0x77697b4c3382 - core::option::expect_failed::hd0fb791ee88ae8a9
                               at /build/rustc-ntAYxy/rustc-1.75.0+dfsg0ubuntu1/library/core/src/option.rs:1985:5
  19:     0x77697bc2d699 - zenoh_transport::common::pipeline::StageIn::push_network_message::h170f37ff16d11688
  20:     0x77697bc25acb - zenoh_transport::common::pipeline::TransmissionPipelineProducer::push_network_message::h37560962fda501bc
  21:     0x77697bc22032 - <zenoh_transport::unicast::universal::transport::TransportUnicastUniversal as zenoh_transport::unicast::transport_unicast_inner::TransportUnicastTrait>::schedule::he921124ad80cc08e
  22:     0x77697b8bdd96 - <zenoh::net::primitives::mux::Mux as zenoh::net::primitives::EPrimitives>::send_push::h56fea9c3b8ac4c8f
  23:     0x77697b88685b - zenoh::net::routing::dispatcher::face::Face::send_push_lazy::h2662885c844bbfa9
  24:     0x77697b884ca4 - zenoh::api::session::SessionInner::resolve_put::ha897222f5ca758e8
  25:     0x77697b68db46 - ze_advanced_publisher_put
  26:     0x77698042f6a6 - _ZN13rmw_zenoh_cpp13PublisherData7publishEPKvRKSt8optionalINS_10ShmContextEE
  27:     0x77698045036b - rmw_publish
  28:     0x776981d971a3 - <unknown>
  29:     0x77697bfa4e26 - <unknown>
  30:     0x77697bfac68f - <unknown>
  31:     0x77697bfbe1b5 - <unknown>
  32:     0x776981f0c5e1 - _ZN6rclcpp8Executor22execute_any_executableERNS_13AnyExecutableE
  33:     0x776981f1d564 - _ZN6rclcpp9executors22SingleThreadedExecutor4spinEv
  34:     0x5ead878e2007 - main
  35:     0x77698162a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x77698162a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  37:     0x5ead878e31c5 - _start
  38:                0x0 - <unknown>
[ros2run]: Aborted
```
</details>

subscribers are not complaining in rolling but at 50.0 Hz it sometimes crashes and if I increase further the frequency I get always a crash.

2025-04-29 10:09 UTC, yellowhatter commented
> Hey I tried with rolling and with this PR but I have some sporadic crashes at the beginning of the publisher, see below.
> ros2 run image_tools cam2image --ros-args -p burger_mode:=true -p width:=1920 -p height:=1080 -p frequency:=50.0
> 
> subscribers are not complaining in rolling but at 50.0 Hz it sometimes crashes and if I increase further the frequency I get always a crash.
> 
> Sometimes it works at 60Hz but ros2 topic hz in this case reports 62.5Hz. Up to 50Hz everything seems fine except for the random crashes on the publisher side.

Hi @mcp-ats ! I will check!

2025-05-07 13:31 UTC, yellowhatter commented
> ros2 run image_tools cam2image

Hi @mcp-ats !
I synchronized SHM branch with recent rolling and zenoh - this fixes the regression on batching wait. The issue you describe is gone.

2025-05-11 07:13 UTC, Yadunund commented
@yellowhatter could you resolve conflicts with `main`?

2025-05-12 07:13 UTC, yellowhatter commented
> @yellowhatter could you resolve conflicts with `main`?

done

2025-05-12 07:53 UTC, mcp-ats commented
@yellowhatter I tried to build it but I get the same issue of the pipeline with the lock file.

I updated rustc via rustup to 1.85.0 but I still get an error about the lock file

`lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?`

Any suggestion?

2025-05-12 08:28 UTC, yellowhatter commented
> @yellowhatter I tried to build it but I get the same issue of the pipeline with the lock file.
> 
> I updated rustc via rustup to 1.85.0 but I still get an error about the lock file
> 
> `lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?`
> 
> Any suggestion?

hello @mcp-ats ! That's my fault sorry. Fixed

2025-05-12 10:18 UTC, mcp-ats commented
thank you @yellowhatter , I tried it and it seems to be working properly now on rolling.

I quickly tested it with one publisher as cam2image tool, with 4K images at 30Hz and 6 subscribers using topic Hz.

I did not notice any problem now.

One more question, I would like to consider Zenoh where I am working but we are committing to Jazzy. Do you think it might be feasible to backport this to Jazzy or do you foresee critical issues?

Thanks!

2025-05-22 15:14 UTC, ahcorde requested changes
can we add in the README some notes about how to enable/disable this feature?

2025-05-26 12:33 UTC, yellowhatter commented
> can we add in the README some notes about how to enable/disable this feature?

sure

2025-05-26 12:36 UTC, yellowhatter commented
> thank you @yellowhatter , I tried it and it seems to be working properly now on rolling.
> 
> I quickly tested it with one publisher as cam2image tool, with 4K images at 30Hz and 6 subscribers using topic Hz.
> 
> I did not notice any problem now.
> 
> One more question, I would like to consider Zenoh where I am working but we are committing to Jazzy. Do you think it might be feasible to backport this to Jazzy or do you foresee critical issues?
> 
> Thanks!

Porting to Jazzy is doable, there are no specific blockers.

2025-05-28 14:46 UTC, ahcorde requested changes

2025-05-28 14:46 UTC, ahcorde commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    std::vector<uint8_t>(
include `<cstdint>`

2025-05-30 10:14 UTC, yellowhatter commented
> thank you @yellowhatter , I tried it and it seems to be working properly now on rolling.
> 
> I quickly tested it with one publisher as cam2image tool, with 4K images at 30Hz and 6 subscribers using topic Hz.
> 
> I did not notice any problem now.
> 
> One more question, I would like to consider Zenoh where I am working but we are committing to Jazzy. Do you think it might be feasible to backport this to Jazzy or do you foresee critical issues?
> 
> Thanks!

Pls check this: https://github.com/ros2/rmw_zenoh/pull/656

2025-05-30 15:50 UTC, yellowhatter commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    std::vector<uint8_t>(
fixed

2025-05-30 15:51 UTC, yellowhatter commented
> can we add in the README some notes about how to enable/disable this feature?

Added

2025-06-03 09:05 UTC, ahcorde approved these changes

2025-06-03 14:55 UTC, Yadunund commented
@yellowhatter i will this PR towards the end of this week.

2025-06-11 07:12 UTC, Yadunund requested changes
@yellowhatter the implementation looks good but I have one concern with thread-safety. Specifically around the access to and lifetime of `const std::optional<ShmContext> & shm` passed to the `publish()` call.

`context_impl->shm()` locks an internal mutex and returns `const std::optional<ShmContext> & shm` but doesn't guarantee mutually exclusive access to the `ShmContext` by two or more publishers whose `publish()` methods could be called concurrently. Further, if the `context_impl` is destroyed, while `publish()` is holding onto `const std::optional<ShmContext> & shm`, it could lead to UB.

Here are my suggestions

1. Make `ShmContext` a class with data members moved to private scope along with a `mutex`. 
2. Add a method to `ShmContext` that accepts a `char * msg_bytes`, locks a mutex, and attempt to allocate it using the `shm_provider`. Then within `publish()`, call this method while passing `msg_bytes` which was initialised as nullptr. If after calling this method, `msg_bytes` is still `nullptr`, default to the usual allocator. 
3. Store a `shared_ptr<ShmContext` within the `context_impl`. Initialize to `nullptr` if SHM not configured. 
4. Update the constructor of `PublisherData` to accept this `shared_ptr<ShmContext>`.  No need to pass it by reference to the `publish()` call. Within `publish()` if this `ShmContext` is `nullptr`, treat it as SHM was not enabled.

let me know what you think?

2025-06-25 18:38 UTC, milidam commented on README.md
> +- `ZENOH_SHM_ALLOC_SIZE`: size (in bytes) of memory to allocate as shared memory arena. Must be a multiply of 4. The default value is 16Mb.
Shouldn't it be 16MB ("in bytes", "16 * 1024 * 1024")?

```suggestion
- `ZENOH_SHM_ALLOC_SIZE`: size (in bytes) of memory to allocate as shared memory arena. Must be a multiply of 4. The default value is 16MB.
```

2025-07-28 09:09 UTC, yellowhatter commented
> @yellowhatter the implementation looks good but I have one concern with thread-safety. Specifically around the access to and lifetime of `const std::optional<ShmContext> & shm` passed to the `publish()` call.
> 
> `context_impl->shm()` locks an internal mutex and returns `const std::optional<ShmContext> & shm` but doesn't guarantee mutually exclusive access to the `ShmContext` by two or more publishers whose `publish()` methods could be called concurrently. Further, if the `context_impl` is destroyed, while `publish()` is holding onto `const std::optional<ShmContext> & shm`, it could lead to UB.
> 
> Here are my suggestions
> 
>     1. Make `ShmContext` a class with data members moved to private scope along with a `mutex`.
> 
>     2. Add a method to `ShmContext` that accepts a `char * msg_bytes`, locks a mutex, and attempt to allocate it using the `shm_provider`. Then within `publish()`, call this method while passing `msg_bytes` which was initialised as nullptr. If after calling this method, `msg_bytes` is still `nullptr`, default to the usual allocator.
> 
>     3. Store a `shared_ptr<ShmContext` within the `context_impl`. Initialize to `nullptr` if SHM not configured.
> 
>     4. Update the constructor of `PublisherData` to accept this `shared_ptr<ShmContext>`.  No need to pass it by reference to the `publish()` call. Within `publish()` if this `ShmContext` is `nullptr`, treat it as SHM was not enabled.
> 
> 
> let me know what you think?

Hi @Yadunund , 
With regards to `SHMContext`, the `PosixShmProvider` that is used there is fully threadsafe, so it is absolutely fine to have concurrent allocations.
With regars to `SHMContext` lifetime, yes, let's then put it from `option` to `shared_ptr` and then rely on `shared_ptr` semantic to have proper lifetime management without additional explicit locking.

2025-07-28 11:04 UTC, YuanYuYuan commented
Pulls: ros2/rmw_zenoh#363
Gist: https://gist.githubusercontent.com/YuanYuYuan/2b9f57fd08f0f435b9ec0baece14168a/raw/4cc3ae8525eaadd998d577b813e07a322eee8c19/ros2.repos
BUILD args: --packages-above-and-dependencies rmw_zenoh_cpp
TEST args: --packages-above rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16635
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24495)](http://ci.ros2.org/job/ci_linux/24495/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18551)](http://ci.ros2.org/job/ci_linux-aarch64/18551/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=3952)](http://ci.ros2.org/job/ci_linux-rhel/3952/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25045)](http://ci.ros2.org/job/ci_windows/25045/)

2025-07-29 06:24 UTC, YuanYuYuan commented
zenoh-c keeps failing to build on Windows due to this error

```txt

      thread 'main' panicked at C:/ci/ws/build/zenoh_cpp_vendor/zenoh_c_vendor-prefix/src/zenoh_c_vendor\buildrs\cbindgen_generator.rs:750:28:

      no sigatures found for building generic z_take_from_loaned

      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

CUSTOMBUILD : warning : build failed, waiting for other jobs to finish... [C:\ci\ws\build\zenoh_cpp_vendor\zenoh_c_vendor-prefix\src\zenoh_c_vendor-build\cargo.vcxproj] [C:\ci\ws\build\zenoh_cpp_vendor\zenoh_c_vendor.vcxproj]
```

@yellowhatter could you have a look?

2025-08-08 16:18 UTC, Yadunund approved these changes
Thanks for iterating on this PR over months! LGTM from my side but please address comments before running CI and merging.

2025-08-08 16:18 UTC, Yadunund commented on README.md
> +> To have Zenoh SHM working, it should be enabled on all Zenoh routers across the message path
```suggestion
> To have Zenoh SHM working, it should be enabled on all Zenoh routers across the message path.
```

2025-08-08 16:18 UTC, Yadunund commented on README.md
> +- `ZENOH_SHM_MESSAGE_SIZE_THRESHOLD`: threshold (in bytes) for ROS message wire size to be sent as SHM buffer. Must be a multiply of 4. The default value is 512.
```suggestion
- `ZENOH_SHM_ALLOC_SIZE`: size (in bytes) of memory to allocate as shared memory arena. Must be a multiple of 4. The default value is 16MB.
- `ZENOH_SHM_MESSAGE_SIZE_THRESHOLD`: threshold (in bytes) for ROS message wire size to be sent as SHM buffer. Must be a multiple of 4. The default value is 512.
```

2025-08-08 16:18 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/zenoh_config.hpp
> +///   - If not set or <= 0, the default value of 1MB is returned.
```suggestion
///   - If not set or <= 0, the default value of 16MB is returned.
```

2025-08-08 16:18 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    auto alloc_result = shm->shm_provider.alloc_gc_defrag(max_data_length);
Nit: Replace auto with explicit type here.

2025-08-08 16:18 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    if (std::holds_alternative<zenoh::ZShmMut>(alloc_result)) {
`#include <variant>` for `std::holds_alternative`

2025-08-11 08:22 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    if (std::holds_alternative<zenoh::ZShmMut>(alloc_result)) {
Resolved in [3f224d7](https://github.com/ros2/rmw_zenoh/pull/363/commits/3f224d749e8c58ca502d2cb60b5044654b13ec70)

2025-08-11 09:03 UTC, JEnoch commented
Pulls: ros2/rmw_zenoh#363
Gist: https://gist.githubusercontent.com/JEnoch/72419d19c51d8cf658a174bf2f5a20c9/raw/4cc3ae8525eaadd998d577b813e07a322eee8c19/ros2.repos
BUILD args: "--continue-on-error" --packages-above-and-dependencies zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
TEST args:  --packages-above zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16691
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24564)](http://ci.ros2.org/job/ci_linux/24564/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18612)](http://ci.ros2.org/job/ci_linux-aarch64/18612/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=4021)](http://ci.ros2.org/job/ci_linux-rhel/4021/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25105)](http://ci.ros2.org/job/ci_windows/25105/)

2025-08-12 15:35 UTC, JEnoch commented
Pulls: ros2/rmw_zenoh#363
Gist: https://gist.githubusercontent.com/JEnoch/eb7066243b40c6606ee411d1ee2fb67f/raw/4cc3ae8525eaadd998d577b813e07a322eee8c19/ros2.repos
BUILD args: "--continue-on-error" --packages-above-and-dependencies zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
TEST args:  --packages-above zenoh_cpp_vendor zenoh_security_tools rmw_zenoh_cpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16698
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24575)](http://ci.ros2.org/job/ci_linux/24575/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18621)](http://ci.ros2.org/job/ci_linux-aarch64/18621/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=4030)](http://ci.ros2.org/job/ci_linux-rhel/4030/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25116)](http://ci.ros2.org/job/ci_windows/25116/)

2025-08-12 15:42 UTC, JEnoch commented on rmw_zenoh_cpp/src/detail/rmw_context_impl_s.cpp
> +#ifdef RMW_ZENOH_BUILD_WITH_SHARED_MEMORY
The `#ifdef RMW_ZENOH_BUILD_WITH_SHARED_MEMORY` has been removed in f5520c37dfd55952003f8ba8e55c93d2c9ec75db.
Since #692 the `shared-memory` feature is always enabled when vendoring `zenoh-c` for `rmw_zenoh`.

2025-08-13 12:41 UTC, JEnoch commented
The failing `ros2doctor.test.test_qos_compatibility` tests on CI are not related to this PR, but to https://github.com/ros2/ros2cli/issues/1088.

2025-08-13 12:41 UTC, merged

2025-08-13 12:42 UTC, JEnoch commented
https://github.com/Mergifyio backport kilted jazzy humble