feat: introduce the advanced publisher and subscriber
osrf/rmw_zenoh pull request #368
Opened 2024-12-31 11:18 UTC by YuanYuYuan

With this PR, we replace the `QueryingSubscriber` and `PublicationCache` (+ a normal publisher)
with the `AdvancedSubscriber` and `AdvancedPublisher`.

NOTE: A deadlock is found when undeclaring advanced subscribers. It will be fixed once https://github.com/eclipse-zenoh/zenoh/pull/1685 is merged and synced with zenoh-c.

2025-01-07 07:58 UTC, YuanYuYuan commented
Update: The deadlock fix has been merged. Mark this PR as ready for review.

2025-01-08 09:32 UTC, YuanYuYuan commented
## Test Check

[ros2.repos](https://github.com/Yadunund/ros2/commit/8792a97457822a5f3dad6503bfb2b0712ef4b539#diff-0b86fcc230a228fb210653f2069d07ee0ab117da02c6471640ae12327835ff4f)

- rclcpp_action
  - 1 - test_client
- rclc_parameter
  - 1 - rclc_parameter_test
- test_rclcpp.log
  - 18 - test_client_scope_cpp__rmw_cyclonedds_cpp (Failed)
  - 47 - test_n_nodes__rmw_fastrtps_cpp (Failed)
  - 74 - test_n_nodes__rmw_zenoh_cpp (Failed)

2025-01-08 15:04 UTC, YuanYuYuan commented
Update: bump up zenoh-cpp version to include the memory leak fix https://github.com/eclipse-zenoh/zenoh-cpp/pull/363.

2025-01-10 01:42 UTC, YuanYuYuan commented
Will rebase once #405 is merged.

2025-01-11 23:53 UTC, Yadunund requested changes
Please see feedback inline.
I have the following additional questions

1. It looks like this PR does not fix #326. But from my experience, it changes the behavior from deterministically failing to failing sometimes. ie, the test is now flaky. Do you observe the same?
2. With `AdvancedSubscribers` do we no longer need to call `Get()`  when we detect an `AdvancedPublisher` with publication cache? This was needed to fix https://github.com/ros2/rmw_zenoh/issues/263.

2025-01-11 23:53 UTC, Yadunund commented on zenoh_cpp_vendor/CMakeLists.txt
> +  VCS_VERSION 85ca060fa4037239ca4102a3a61f96626cc6b434
Please replace the comment above and below to include changes in this commit hash.

2025-01-11 23:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/graph_cache.hpp
> -  void set_querying_subscriber_callback(
You'll also need to delete `querying_subs_cbs_` and update `graph_cache.cpp` to not iterate over `querying_subs_cbs_`

2025-01-11 23:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +  adv_pub_opts.sample_miss_detection = true;
Looking at the [documentation for this option](https://zenoh-cpp.readthedocs.io/en/latest/ext.html#_CPPv4N5zenoh3ext10SessionExt24AdvancedPublisherOptions21sample_miss_detectionE), it sounds like this should be set `true` only if `adapted_qos_profile.reliability == RMW_QOS_POLICY_RELIABILITY_RELIABLE`? Could you clarify how this differs from setting `pub_opts.reliability = Z_RELIABILITY_RELIABLE`?

2025-01-11 23:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> -      pub_ke, std::move(pub_cache_opts), &result);
We previously needed to do this to fix https://github.com/ros2/rmw_zenoh/issues/263. Can you confirm that we no longer need to explicitly call `QueryingSubscriber::get()` when we discover an AdvancedPublisher in the graph?

2025-01-11 23:53 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_subscription_data.cpp
> +    adv_sub_opts.recovery->periodic_queries_period_ms = 1000;
Again looking at the [documentation](https://zenoh-cpp.readthedocs.io/en/latest/ext.html#_CPPv4N5zenoh3ext10SessionExt25AdvancedSubscriberOptions15RecoveryOptions26periodic_queries_period_msE), it sounds like recovery options should only be enabled if reliability is `RELIABLE`. Could you clarify on the behavior?

2025-01-13 08:23 UTC, YuanYuYuan commented on zenoh_cpp_vendor/CMakeLists.txt
> +  VCS_VERSION 85ca060fa4037239ca4102a3a61f96626cc6b434
Thanks. This was out of sync. We don't need to change it in this PR.

2025-01-13 08:29 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/graph_cache.hpp
> -  void set_querying_subscriber_callback(
Done in 9cc776bd8cc7fddfea8dec0ad703a22d3a6c96d3

2025-01-13 08:34 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +  adv_pub_opts.sample_miss_detection = true;
The reliability option can still be set by the normal publisher option. See [here](https://github.com/ZettaScaleLabs/rmw_zenoh/blob/9cc776bd8cc7fddfea8dec0ad703a22d3a6c96d3/rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp?plain=1#L128). The reliability in zenoh is based on TCP reliability per see. The sample_miss_detection here is a custom data retransmission feature cached on the publisher side in the sense of transient_local duriability.

2025-01-13 08:37 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> -      pub_ke, std::move(pub_cache_opts), &result);
We should no longer need this hack. Otherwise, it's a bug in zenoh.

2025-01-13 08:38 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_subscription_data.cpp
> +    adv_sub_opts.recovery->periodic_queries_period_ms = 1000;
Similarly, answered in https://github.com/ros2/rmw_zenoh/pull/368#discussion_r1912826044.

2025-01-13 08:46 UTC, YuanYuYuan commented
> Please see feedback inline. I have the following additional questions
> 
>     1. It looks like this PR does not fix [[Test Failure] rclcpp_action / test_client #326](https://github.com/ros2/rmw_zenoh/issues/326). But from my experience, it changes the behavior from deterministically failing to failing sometimes. ie, the test is now flaky. Do you observe the same?
> 
>     2. With `AdvancedSubscribers` do we no longer need to call `Get()`  when we detect an `AdvancedPublisher` with publication cache? This was needed to fix [Subscribers sometimes not getting messages from topics using durability transient_local #263](https://github.com/ros2/rmw_zenoh/issues/263).
Here’s an improved version of your paragraph with clearer phrasing and a more professional tone:

1. This PR does not resolve the issue reported in #326. Based on the investigation, the root cause lies in the inappropriate synchronization assumptions in the test. We have also observed similar failures (slightly more often) when using the previous `QueryingSubscriber` implementation. To address this issue, we can either make the local publisher-to-subscriber action a blocking call or modify the test itself.

2. We expect the issue will be resolved. So no longer need the hack :smile:

2025-01-13 08:48 UTC, YuanYuYuan commented
Redid the test with the [repos](https://github.com/Yadunund/ros2/commit/87d14774e8609d8201d9f15a8421081c628bb1d6). No new failures are found.

- rclcpp_action/test_client
- rclc_parameter/rclc_parameter_test

2025-01-14 17:48 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_subscription_data.cpp
> +    adv_sub_opts.recovery->periodic_queries_period_ms = 1000;
Could we add some comments on why a value of `1000` is appropriate for `periodic_queries_period_ms`?

2025-01-14 18:05 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_subscription_data.cpp
> -      zenoh::QueryConsolidation(zenoh::ConsolidationMode::Z_CONSOLIDATION_MODE_NONE);
And it does not look like there is a way to set these parameters anymore. Can you confirm that the behavior with the AdvancedSubscriber will match the expectations of the old implementation?

2025-01-16 06:04 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_subscription_data.cpp
> -      zenoh::QueryConsolidation(zenoh::ConsolidationMode::Z_CONSOLIDATION_MODE_NONE);
Yes. They're preset in the same way https://github.com/eclipse-zenoh/zenoh/blob/26d67de043efe327befd0bbfb29c76a5157f1baf/zenoh-ext/src/advanced_subscriber.rs?plain=1#L615.

2025-01-22 08:49 UTC, YuanYuYuan commented
Now we set the advanced pub/sub to map the ROS2 QoS according to the following table.

- AdvPub

|Option                          |ROS2 QoS                              |
|-                               |-                                     |
|publisher_detection             |Durability::TransientLocal            |
|cache                           |Durability::TransientLocal or Reliable|
|cache->max_samples              |Depth                                 |
|sample_miss_detection           |Reliable                              |
|sample_miss_detection->heartbeat|Reliable                              |
|Z_RELIABILITY_RELIABLE          |Reliable                              |
|Z_CONGESTION_CONTROL_BLOCK      |Reliable & History::KeepALL           |

- AdvSub

|Option                                          |ROS2 QoS                  |
|-                                               |-                         |
|subscriber_detection                            |Durability::TransientLocal|
|sample_miss_detection                           |Durability::TransientLocal|
|history->detect_late_publishers                 |Durability::TransientLocal|
|history->max_samples                            |Depth                     |
|recovery                                        |Reliable                  |
|recovery->last_sample_miss_detection = heartbeat|Reliable                  |

2025-01-23 22:55 UTC, Yadunund commented
We discussed this today and we agreed to hold merging this PR until we test the changes here on more complex applications to gauge whether the constants adopted are appropriate.

2025-02-06 21:30 UTC, Yadunund commented
We discussed this again today and agreed to convert this to a draft PR until https://github.com/eclipse-zenoh/zenoh/pull/1753 is merged and zenoh version here is updated. Along with this change, we will also be disabling recovery and sample missed options as it does not fit the typical ROS use case.

2025-02-07 07:45 UTC, YuanYuYuan commented
The recovery option has been removed in https://github.com/ros2/rmw_zenoh/pull/368/commits/0e4b99d7363bcc61e9fa6431dec5c3a2380547d3

2025-02-12 09:53 UTC, JEnoch commented
I created #457 to address the possible usage of `recovery` and `sample_miss_detection` options.
Those options are only required to benefit end-to-end reliability.
They are not required to implement `TRANSIENT_LOCAL` QoS which is the goal of this PR, as a replacement of the deprecated QueryingSubscriber and Publication Cache.

As soon as #456 (that includes https://github.com/eclipse-zenoh/zenoh/pull/1753) is merged, I think this PR is good to go.

2025-02-14 20:26 UTC, Yadunund requested changes
Tested with latest zenoh bump and I can confirm that rclcpp_action/test_client passes 🎉 

However, I'm concerned with one change which i've flagged below.

2025-02-14 20:26 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    adv_pub_opts.cache->max_samples = adapted_qos_profile.depth;
Based on this logic, a PubCache is created even if durability is volatile as long as reliability is reliable. Isn't this a change in behavior? Why do we need to check for reliability here?

2025-02-17 07:00 UTC, YuanYuYuan commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    adv_pub_opts.cache->max_samples = adapted_qos_profile.depth;
It was needed if "end-to-end" reliability is required. But since we have decided to exclude it from this PR, let's roll back to its original setting.

2025-02-18 19:22 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/rmw_publisher_data.cpp
> +    adv_pub_opts.cache->max_samples = adapted_qos_profile.depth;
Sounds good, I pushed some minor changes in https://github.com/ros2/rmw_zenoh/pull/368/commits/15d522a8abe6f183999e4942febd77c19f160703

2025-02-18 19:26 UTC, Yadunund approved these changes
LGTM! Thanks for iterating on this PR to find the right fix! We can finally close out #326

2025-02-18 19:46 UTC, merged

2025-02-18 19:46 UTC, Yadunund commented
@mergifyio backport jazzy humble