Use z_check and z_drop instead of zc_liveliness_XX
osrf/rmw_zenoh pull request #69
Opened 2023-11-20 12:06 UTC by JEnoch

Following https://github.com/eclipse-zenoh/zenoh-c/pull/195 the workaround described [here](https://github.com/ros2/rmw_zenoh/pull/67#issuecomment-1814178040) can be rolled back.

The API was indeed missing to call `z_check()` on a `zc_owned_liveliness_token_t`.
The undefined symbol error calling `z_drop()` was probably an build environment issue.

2023-11-20 14:42 UTC, Yadunund requested changes
Thanks for fixing the macros @JEnoch! I think there might have been a search + replace error which added an extra `(` after `z_drop`.

2023-11-20 14:42 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +  z_drop((z_move(node_data->token));
```suggestion
  z_drop(z_move(node_data->token));
```

2023-11-20 14:42 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +        z_drop((z_move(publisher_data->token));
```suggestion
        z_drop(z_move(publisher_data->token));
```

2023-11-20 14:42 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +    z_drop((z_move(publisher_data->token));
```suggestion
    z_drop(z_move(publisher_data->token));
```

2023-11-20 14:42 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +        z_drop((z_move(sub_data->token));
```suggestion
        z_drop(z_move(sub_data->token));
```

2023-11-20 14:42 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +    z_drop((z_move(sub_data->token));
```suggestion
    z_drop(z_move(sub_data->token));
```

2023-11-20 15:14 UTC, JEnoch commented
Oups! Sorry about that... Fixed!

2023-11-20 15:38 UTC, Yadunund commented
I'm still seeing the same undefined symbol error at runtime
```bash
/opt/ros/iron/lib/demo_nodes_cpp/listener: symbol lookup error: /home/yadunund/ws_rmw/install/rmw_zenoh_cpp/lib/librmw_zenoh_cpp.so: undefined symbol: _Z6z_dropI27zc_owned_liveliness_token_tEN15zenoh_drop_typeIT_E4typeEPS2_

```

In fact, on MacOS i'm unable to even compile with apple clang + ld linker
```bash
ld: Undefined symbols:
  zenoh_drop_type<zc_owned_liveliness_token_t>::type z_drop<zc_owned_liveliness_token_t>(zc_owned_liveliness_token_t*), referenced from:
      rcpputils::scope_exit<rmw_create_node::$_4>::~scope_exit() in rmw_zenoh.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [librmw_zenoh_cpp.dylib] Error 1
make[1]: *** [CMakeFiles/rmw_zenoh_cpp.dir/all] Error 2
make: *** [all] Error 2
make: INTERNAL: Exiting with 11 jobserver tokens available; should be 10!
---
Failed   <<< rmw_zenoh_cpp [13.8s, exited with code 2]
```

2023-11-20 16:07 UTC, clalancette commented
> /opt/ros/iron/lib/demo_nodes_cpp/listener: symbol lookup error: /home/yadunund/ws_rmw/install/rmw_zenoh_cpp/lib/librmw_zenoh_cpp.so: undefined symbol: _Z6z_dropI27zc_owned_liveliness_token_tEN15zenoh_drop_typeIT_E4typeEPS2_

Yeah, I'm seeing this as well with this PR in place.  Not sure what is going on there.

2023-11-20 16:45 UTC, JEnoch commented
Weird! The builds with both `iron-ros-base` and `rolling-ros-base` Docker images are passing here in [Actions](https://github.com/ros2/rmw_zenoh/actions/runs/6932064149?pr=69), as well as on my Ubuntu 22.04/Rolling VM.
Could it be related to compiler/linker version ?
Mine are `gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)` and `GNU ld (GNU Binutils for Ubuntu) 2.38`

2023-11-20 16:52 UTC, Yadunund commented
> Weird! The builds with both `iron-ros-base` and `rolling-ros-base` Docker images are passing here in [Actions](https://github.com/ros2/rmw_zenoh/actions/runs/6932064149?pr=69), as well as on my Ubuntu 22.04/Rolling VM. Could it be related to compiler/linker version ? Mine are `gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)` and `GNU ld (GNU Binutils for Ubuntu) 2.38`

To clarify, on Ubuntu 22.04 + Iron/Rolling, the packages build without any errors. But the linker error is thrown when the `z_drop()` is called on the liveliness token when we cleanup the node.
To reproduce this,
```bash
cd ~/ws_rmw
source install/setup.bash
export RMW_IMPLEMENTATION=rmw_zenoh_cpp
ros2 run demo_nodes_cpp listener

## Then terminal the node with Ctrl+C

/opt/ros/iron/lib/demo_nodes_cpp/listener: symbol lookup error: /home/yadunund/ws_rmw/install/rmw_zenoh_cpp/lib/librmw_zenoh_cpp.so: undefined symbol: _Z6z_dropI27zc_owned_liveliness_token_tEN15zenoh_drop_typeIT_E4typeEPS2_

```

2023-11-22 15:20 UTC, JEnoch commented
Oh! OK, thanks for the clarification.
I managed to reproduce, and also saw the issue has actually been fixed in zenoh-c by https://github.com/eclipse-zenoh/zenoh-c/pull/197.
The error disappeared for me after updating zenoh-c.

2023-11-23 04:18 UTC, Yadunund approved these changes
Tested with the latest zenoh-c and works great! Thanks for following up!

2023-11-23 04:18 UTC, merged