Support basic QoS settings
osrf/rmw_zenoh pull request #91
Opened 2024-01-11 11:15 UTC by Yadunund

# TODO
- [ ] Call ze_querying_subscriber_get() when a TRANSIENT_LOCAL publisher is discovered with matching endpoints.
- [ ] Update QoS compatibility checking methods.

This PR provides support for the following QoS settings:
- History Depth (History is always set to `KEEP_LAST`)
- Durability (`VOLATILE` and `TRANSIENT_LOCAL`)
- Reliability (`RELIABLE` and `BEST_EFFORT`)

It also updates the liveliness tokens to forward serialized qos information. Graph introspection methods are also updated.
Before testing, remember to restart any running zenoh routers and kill existing ros2 daemons.

Test below where publisher has durability `VOLATILE` buyt subsciption has durability `TRANSIENT_LOCAL`. The QoS properties should be populated when 

```bash
# terminal 1
ros2 topic pub /chatter std_msgs/msg/String 'data: qos_test'
```

```bash
# terminal 2
ros2 topic echo /chatter --qos-durability transient_local 
```

```bash
# terminal 3

ros2 topic info -v /chatter

Type: std_msgs/msg/String

Publisher count: 1

Node name: _ros2cli_1291445
Node namespace: /
Topic type: std_msgs/msg/String
Topic type hash: INVALID
Endpoint type: PUBLISHER
GID: 00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (10)
  Durability: VOLATILE
  Lifespan: 0 nanoseconds
  Deadline: 0 nanoseconds
  Liveliness: SYSTEM_DEFAULT
  Liveliness lease duration: 0 nanoseconds

Subscription count: 1

Node name: _ros2cli_1291563
Node namespace: /
Topic type: std_msgs/msg/String
Topic type hash: INVALID
Endpoint type: SUBSCRIPTION
GID: 00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  History (Depth): KEEP_LAST (5)
  Durability: TRANSIENT_LOCAL
  Lifespan: 0 nanoseconds
  Deadline: 0 nanoseconds
  Liveliness: SYSTEM_DEFAULT
  Liveliness lease duration: 0 nanoseconds
```

2024-01-18 06:51 UTC, Yadunund commented
With the qos methods implemented, `actions` also work**

```bash
# terminal 1
ros2 run action_tutorials_cpp fibonacci_action_server 
```

```bash
# terminal 2
ros2 run action_tutorials_cpp fibonacci_action_client 


[INFO] [1705560511.794785988] [fibonacci_action_client]: Sending goal
[INFO] [1705560511.794917049] [rmw_zenoh_cpp]: [rmw_send_request]
[INFO] [1705560511.796353630] [rmw_zenoh_cpp]: [rmw_take_response]
[INFO] [1705560511.796443000] [fibonacci_action_client]: Goal accepted by server, waiting for result
[INFO] [1705560511.796472320] [rmw_zenoh_cpp]: [rmw_send_request]
[INFO] [1705560511.796863030] [fibonacci_action_client]: Next number in sequence received: 0 1 1 
[INFO] [1705560512.797255312] [fibonacci_action_client]: Next number in sequence received: 0 1 1 2 
[INFO] [1705560513.797292703] [fibonacci_action_client]: Next number in sequence received: 0 1 1 2 3 
[INFO] [1705560514.797283484] [fibonacci_action_client]: Next number in sequence received: 0 1 1 2 3 5 
[INFO] [1705560515.797236973] [fibonacci_action_client]: Next number in sequence received: 0 1 1 2 3 5 8 
^C[INFO] [1705560516.232405866] [rclcpp]: signal_handler(signum=2)

```

** Killing the client process does not cancel the goal and the server will continue to publish feedback messages. This should be resolved with @clalancette's fixes to service/clients.

2024-01-23 18:03 UTC, clalancette requested changes
Besides what I left inline, I have two overall comments:

1.  When I'm running this code with `ros2 run demo_nodes_cpp talker`, I'm seeing a segfault on exit.  That doesn't seem to be the case on the `rolling` branch, so I think it bears looking into.
2.  I did some testing of TRANSIENT_LOCAL vs. VOLATILE on DDS and on Zenoh.  The one place where they differ is if the publisher is volatile, and the subscription is transient_local.  With Fast-DDS, in that case no data is transmitted and we get an Incompatible QoS warning.  With this PR in place, we don't get the incompatible QoS warning and data *is* transmitted.  If possible, I think it would be best if we could keep the semantics the same (at least for now).

2024-01-23 18:03 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +std::string qos_to_keyexpr(rmw_qos_profile_t qos)
Can you give an idea of what the keyexpression for QoS profiles looks like currently?  It kind of seems to me that it would be filled with enum numbers, but I could be wrong.

2024-01-23 18:03 UTC, clalancette commented on rmw_zenoh_cpp/CMakeLists.txt
> +find_package(rmw_dds_common REQUIRED)
I'm not a huge fan of linking to `rmw_dds_common`, mostly because it could confuse people about what `rmw_zenoh_cpp` is.  At the same time, there is quite a bit of code in https://github.com/ros2/rmw_dds_common/blob/rolling/rmw_dds_common/src/qos.cpp that would be somewhat unfortunate to duplicate.

I guess I'll ask; how compatible are the current QoS settings between Zenoh and DDS?  What are the things that are always going to remain different between them?

2024-01-23 18:03 UTC, clalancette commented on rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
> +    enabled: { router: true, peer: true, client: false },
Can you explain a little more about what this change does, and why we had it set to `false` before?

2024-01-23 18:03 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +  sscanf(history_parts[1].c_str(), "%zu", &qos.depth);
I don't think we should use `sscanf` to turn a string into an integer here.  It is too easy to misuse it, it doesn't report errors that well, and it is probably slow.

Instead I think we should probably use `strtoul`, with code similar to https://github.com/ros2/rmw_zenoh/blob/d49f9763253417da68062cadabfe30a2e0450f2b/rmw_zenoh_cpp/src/rmw_zenoh.cpp#L2168-L2188

2024-01-24 01:52 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +std::string qos_to_keyexpr(rmw_qos_profile_t qos)
I tried to explain in the docstring above this function defn. Copied below for reference.
```
/**
 * <ReliabilityKind>:<DurabilityKind>:<HistoryKind>,<HistoryDepth>"
 * Where:
 *  <ReliabilityKind> - enum value from rmw_qos_reliability_policy_e.
 *  <DurabilityKind> - enum value from rmw_qos_durability_policy_e.
 *  <HistoryKind> - enum value from rmw_qos_history_policy_e.
 *  <HistoryDepth> - The depth number.
 */
 ```
 
 Would it be clearer to include an example?

2024-01-24 01:56 UTC, Yadunund commented on rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
> +    enabled: { router: true, peer: true, client: false },
I included a note in the PR description
```
> Note: PublicationCache only works when time-stamping is enabled for peers in the zenoh configs.
```
I'll add some documentation inside the config

2024-01-24 03:34 UTC, Yadunund commented
> When I'm running this code with ros2 run demo_nodes_cpp talker, I'm seeing a segfault on exit. That doesn't seem to be the case on the rolling branch, so I think it bears looking into.

I was able to reproduce this with a clean build and uncovered why we're seeing this after merging the latest `rolling` into this branch:
1. Turns out we've had [shm enabled in the session config](https://github.com/ros2/rmw_zenoh/blob/d49f9763253417da68062cadabfe30a2e0450f2b/rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5#L237) while it is [disbaled in the router config](https://github.com/ros2/rmw_zenoh/blob/d49f9763253417da68062cadabfe30a2e0450f2b/rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5#L237). But it should have been disabled in the session config as we observed memory leaks in shm and decided to not have it enabled by default.
2. As a result, we've been initializing [shm_manager in all sessions](https://github.com/ros2/rmw_zenoh/blob/a9b424505c55411dd37db402eae91663673980e8/rmw_zenoh_cpp/src/rmw_init.cpp#L181-L193) and actually getting memory for the published messages [from the shm_manager](https://github.com/ros2/rmw_zenoh/blob/a9b424505c55411dd37db402eae91663673980e8/rmw_zenoh_cpp/src/rmw_zenoh.cpp#L879-L881).
3. I tracked the cause of the segfault to be [these lines that drop the shm_manager](https://github.com/ros2/rmw_zenoh/blob/a9b424505c55411dd37db402eae91663673980e8/rmw_zenoh_cpp/src/rmw_init.cpp#L348-L350) when shutting down the context. 
4. In https://github.com/ros2/rmw_zenoh/pull/95, we disabled all other features including `zenoh/shared-memory` and I think that's why we're seeing the sefault.
5.  I've pushed https://github.com/ros2/rmw_zenoh/pull/91/commits/a9b424505c55411dd37db402eae91663673980e8 which disables shm in the session config which resolves the issue. I also tried enabling build with `zenoh/shm-manager` feature but the segfault still happens if the config enables shm. We need more insights from zettascale on what other features we need to enable, eg `unstable`. For now I think disabling shm in the session config is the best way forward.

2024-01-24 04:28 UTC, Yadunund commented
> I did some testing of TRANSIENT_LOCAL vs. VOLATILE on DDS and on Zenoh. The one place where they differ is if the publisher is volatile, and the subscription is transient_local. With Fast-DDS, in that case no data is transmitted and we get an Incompatible QoS warning. With this PR in place, we don't get the incompatible QoS warning and data is transmitted. If possible, I think it would be best if we could keep the semantics the same (at least for now).

Thanks for doing that test. I'm not sure if I agree with that behavior. Imo the subscription should still continue receiving new messages from the publisher BUT with a warning printed that older messages will not be received. But having said that, I'm surprised the implementation here does not throw the same error since we fully reuse [rmw_dds_common::qos_profile_check_compatibility](https://github.com/ros2/rmw_dds_common/blob/ae7df87714cccf4d7ad54dcd00201f4931f2060f/rmw_dds_common/src/qos.cpp#L87-L139). 🤔 
Looking into it.

2024-01-24 04:33 UTC, Yadunund commented on rmw_zenoh_cpp/CMakeLists.txt
> +find_package(rmw_dds_common REQUIRED)
imo the biggest difference is the lack of QoS settings, specifically `reliability` for publishers. Zenoh separates control over message resending, memory usage (buffering) and message dropping. 
The reason I chose to reuse some of the methods from `rmw_dds_common` is to ensure qos compatibility checks and generation of adapted qos profiles will remain the same for users coming from DDS based rmws.

2024-01-24 04:59 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +  sscanf(history_parts[1].c_str(), "%zu", &qos.depth);
Done https://github.com/ros2/rmw_zenoh/pull/91/commits/44d7627ec3f0e469b1d7c41f298b55fcce368d18

2024-01-24 04:59 UTC, Yadunund commented on rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
> +    enabled: { router: true, peer: true, client: false },
Done https://github.com/ros2/rmw_zenoh/pull/91/commits/34f2623fe781ad68fcf0abf7107cd99dd341de89

2024-01-24 05:25 UTC, Yadunund commented
> > I did some testing of TRANSIENT_LOCAL vs. VOLATILE on DDS and on Zenoh. The one place where they differ is if the publisher is volatile, and the subscription is transient_local. With Fast-DDS, in that case no data is transmitted and we get an Incompatible QoS warning. With this PR in place, we don't get the incompatible QoS warning and data is transmitted. If possible, I think it would be best if we could keep the semantics the same (at least for now).
> 
> Thanks for doing that test. I'm not sure if I agree with that behavior. Imo the subscription should still continue receiving new messages from the publisher BUT with a warning printed that older messages will not be received. But having said that, I'm surprised the implementation here does not throw the same error since we fully reuse [rmw_dds_common::qos_profile_check_compatibility](https://github.com/ros2/rmw_dds_common/blob/ae7df87714cccf4d7ad54dcd00201f4931f2060f/rmw_dds_common/src/qos.cpp#L87-L139) and hence my comment here [#91 (comment)](https://github.com/ros2/rmw_zenoh/pull/91#discussion_r1464295727). 🤔 Looking into it.

After some digging, with `Fast-DDS`, the message is thrown because of qos incompatibility from the [default_incompatibile_qos_callback](https://github.com/ros2/rclcpp/blob/a5221336f64e9754377e5391663dc6c7f3da3975/rclcpp/src/rclcpp/subscription_base.cpp#L133C15-L133C48). Since we don't support events yet, I think this isn't being flagged. But also since the zenoh transport can handle such qos mismatches, I don't think we will need to flag it? It's one of the reasons I left this [todo](https://github.com/ros2/rmw_zenoh/blob/52d16cb5027bb58f9ebb379b36428f149dea09f2/rmw_zenoh_cpp/src/detail/graph_cache.cpp#L688) in the impl here. I'm not sure if we should report incompatibility to match DDS behavior since zenoh transport can handle the differences.

2024-01-26 04:03 UTC, Yadunund commented
Went back and forth on whether to rely on a blocking vs non-blocking channel for making the liveliness query at startup. I think we should stick to blocking for now (https://github.com/ros2/rmw_zenoh/pull/91/commits/78ab5a18f9c3deda2490246ad5f4115b10d42bea). Rationale is fewer threads needed (i think) and perhaps more accurate results when using CLI tools like `ros2 topic list` as the graph cache will be fully updated by the end of `rmw_init`.

2024-01-31 03:29 UTC, Yadunund commented
I've set the `SystemDefault` depth to 1 via https://github.com/ros2/rmw_zenoh/pull/91/commits/1298abd1ea3124b4a1bca54c4eec6795206766d8.

The depth is 1 in [rmw_cyclonedds](https://github.com/ros2/rmw_cyclonedds/blob/f3d802e3c7ae3331e88868cda010bf9c17dd0655/rmw_cyclonedds_cpp/src/rmw_node.cpp#L2196-L2197).

2024-02-06 14:01 UTC, clalancette requested changes
I did another review pass.  This is looking pretty good in general, just a few things to cleanup and followup on.

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/CMakeLists.txt
> +find_package(rmw_dds_common REQUIRED)
In order to move forward with this PR, I say we take the dependency for now.  But I'm also going to suggest that we open up a new issue to revisit this, and possibly drop the dependency in the future.

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +    ss << static_cast<int>(id.id[i]);
This is changing the string representation of the zid from XX.YY.ZZ to XXYYZZ.  Can you explain the reasoning behind this?

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +std::string qos_to_keyexpr(rmw_qos_profile_t qos)
Yeah, I think an example would help, thanks.

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +}
Looking at the implementation of this function, it actually seems like this is unnecessarily iterating over the string twice: once to find the delimiters, and then again to copy the substrings into the vector.

But we should be able to make this more efficient by just iterating once.  Basically we iterate, looking for the delimiter, and copying into the result as we go along.  Something like this:

```
std::vector<std::string> split_keyexpr(
  const std::string & keyexpr,
  const char delim)
{
  std::vector<std::string> result = {};
  size_t start = 0;
  size_t end = keyexpr.find(delim);
  while (end != std::string::npos) {
    result.push_back(keyexpr.substr(start, end - start));
    start = end + 1;
    end = keyexpr.find(delim, start);
  }
  result.push_back(keyexpr.substr(start));
  return result;
}
```

In some basic benchmarking locally, this is about twice as fast as the current implementation.

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +#define RMW_ZENOH_DEFAULT_HISTORY_DEPTH 1;
I think we agreed to change this to 10, 100, or possibly 256 (the default Zenoh queue size).

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +  // If a depth of 0 was provided, the RMW implementation can set the depth to a default.
```suggestion
  // If a depth of 0 was provided, the RMW implementation should choose a suitable default.
```

2024-02-06 14:01 UTC, clalancette commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +  else {
```suggestion
  } else {
    // Create a regular subscriber for all other durability settings.
```

2024-02-07 04:34 UTC, Yadunund commented on rmw_zenoh_cpp/CMakeLists.txt
> +find_package(rmw_dds_common REQUIRED)
Done https://github.com/ros2/rmw_zenoh/issues/104

2024-02-07 04:35 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +    ss << static_cast<int>(id.id[i]);
This was a minor "optimization" I did to reduce the number of bytes in the keyexpression and reduce bandwidth.

2024-02-07 04:36 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +std::string qos_to_keyexpr(rmw_qos_profile_t qos)
Done https://github.com/ros2/rmw_zenoh/pull/91/commits/c807b34855ffbb454c0056c2fa02d1759cf64116

2024-02-07 06:40 UTC, Yadunund commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +}
Doh I don't know why the original was so complicated. Updated to your more efficient approach https://github.com/ros2/rmw_zenoh/pull/91/commits/009837101b2f70e3b6cae2db88a45cbbd742a4cb

2024-02-07 07:05 UTC, Yadunund commented on rmw_zenoh_cpp/src/rmw_zenoh.cpp
> +#define RMW_ZENOH_DEFAULT_HISTORY_DEPTH 1;
Done https://github.com/ros2/rmw_zenoh/pull/91/commits/e85d45d6d3796b08dc7983562aa025d5ed4a8a56

2024-02-07 13:08 UTC, clalancette requested changes
I've left one more relatively minor change.  Once that is done, I think this is good to go in.

2024-02-07 13:08 UTC, clalancette commented on rmw_zenoh_cpp/src/detail/liveliness_utils.cpp
> +  int64_t num = strtol(history_parts[1].c_str(), &endptr, 10);
Given that `qos.depth` is a [size_t](https://github.com/ros2/rmw/blob/9b3d9d0e3021b7a6e75d8886e3e061a53c36c789/rmw/include/rmw/types.h#L574), I think we should use `strtoul` here:

```suggestion
  unsigned long num = strtoul(history_parts[1].c_str(), &endptr, 10);
```

2024-02-07 16:17 UTC, clalancette approved these changes
I just pushed some minor cpplint fixes.  With that, I'm happy with this, so once CI comes back green I'm going to go ahead and merge this.

2024-02-07 16:24 UTC, merged